Completed homework_1
MastersAcademy/ruby-course-2018 pull request #10
Opened 2018-11-09 14:59 UTC by vladvovk2

2018-11-10 11:11 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/01_task.rb
> +def utc_zone
Скрипт повинен на вхід приймати таймзону в текстовому виглаяді (див. завдання)

2018-11-10 11:11 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/01_task.rb
> +  one = "+0#{ARGV.first}:00"
1. Краще ```ARGV.first``` поміщати в зрозуміло названу змінну, це зручніше коли читаєш код і не потрібно кожен раз бігати по масиву ```ARGV```
2. Потрібно намагатись називати зрозуміло змінні, ```one``` і ```two``` ні про що не каже

2018-11-10 11:11 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/01_task.rb
> +  ARGV.first.length <= 1 ? user_input = one : user_input = two
Якщо вже використовуєш цю структуру, краще привести до вигляду
```ruby
  result = condition ? value_1 : value_2
```
а не сетити змінну при виконанні умови, ще й в тернарному операторі

2018-11-10 12:07 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/02_task.rb
> +    while (line = file.gets)
1. Ітераторам віддається перевага перед циклами
```ruby
  File.open("#{file_path}", 'r') do |file|
    file.each do |line|
      # implementation
    end
  end
```
2. Результат виконання методу ```set_color``` потрібно помістити в змінну перед ітератором чи циклом, інакше колір буде визначатись при кожній ітерації, а не за один раз

2018-11-10 12:07 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/02_task.rb
> +  lines.each { |l| puts l }
Зайве поміщати кожен ```line``` в масив ```lines```, потім бігти по цьому масиву і виводити колір, можна в циклі (а краще ітераторі) відразу виводити результат
```ruby
  puts line.colorize(color)
```

2018-11-10 12:43 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/05_task.rb
> +  lines.select.with_index { |l, i| puts i + 1  if l.include? ARGV.last}
Не виправдане використання ```select```, оскільки вибирати саму строку не потрібно, потрібно лише вивести номер сторки. Доречі, в завданні вказано, що потрібно знайти номер строки де ВПЕРШЕ зустрічається заданий рядок, цей код поверне всі номери строк із співпадіннями в текстовому файлі

2018-11-10 12:59 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/06_task.rb
> +	attr_accessor :arg1, :arg2
Неправильне форматування коду, потрібно робити відступ у 2 пробіли

2018-11-10 12:59 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/06_task.rb
> +		@arg1 = arg1.to_i
Якщо оголошуєш ```attr_accessor```, то логічно використовувати сеттер
```ruby
  self.arg1 = arg1.to_i
```
інакше достатньо було б оголосити тільки ```attr_reader```

2018-11-10 12:59 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/06_task.rb
> +first  = ARGV.first
Потрібно називати змінні зрозуміло, можна за таким прикладом
```ruby
  first_argument, second_argument, operation = ARGV
```

2018-11-10 13:03 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/07_task.rb
> +first  = (1..20).collect { rand(1..30) }
Скрипт повинен приймати масив при виклику, а не формувати його самостійно

2018-11-10 13:03 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/07_task.rb
> +def random_obj(array)
В цьому методі немає сенсу, достатньо на отриманому масиві викликати метод ```sample```

2018-11-10 13:09 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/08_task.rb
> +def random_obj(array)
Назва методу не відповідає його внутрішній логіці

2018-11-10 13:09 UTC, Patriarh22 commented on ruby_basic/vlad.vovk/homework_1/08_task.rb
> +    array.sort.reverse
Метод ```sort``` може приймати на вхід блок, де вказується порядок сортування, відповідно по масиву відбудеться лише один прохід, а не два, як зараз

2018-11-11 22:08 UTC, slenderock commented on ruby_basic/vlad.vovk/homework_1/06_task.rb
> +	def divide
Зверни увагу, що всередині методу, для опису rescue ти можеш використовувати ось таку синтаксичну структуру:
```
def divide
  arg1 / arg2
rescue ZeroDivisionError
  "hi. dont do that again"	
end
```
На данному етапі не критично, просто для саморозвитку.

2018-11-11 22:49 UTC, slenderock requested changes
В пріоритеті вказані @Patriarh22  правки по умовах завдання. 
Опціонально правки по стайлгайдам

2018-11-14 18:26 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/01_task.rb
> +  ARGV.first.length <= 1 ? user_input = one : user_input = two
виправлено

2018-11-14 18:47 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/01_task.rb
> +def utc_zone
виправлено

2018-11-14 18:47 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/01_task.rb
> +  one = "+0#{ARGV.first}:00"
виправлено

2018-11-14 18:51 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/02_task.rb
> +    while (line = file.gets)
виправлено

2018-11-14 18:52 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/02_task.rb
> +  lines.each { |l| puts l }
виправлено

2018-11-14 19:08 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/05_task.rb
> +  lines.select.with_index { |l, i| puts i + 1  if l.include? ARGV.last}
виправлено

2018-11-14 19:11 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/06_task.rb
> +first  = ARGV.first
виправлено

2018-11-14 19:14 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/08_task.rb
> +def random_obj(array)
виправлено

2018-11-14 19:21 UTC, vladvovk2 commented on ruby_basic/vlad.vovk/homework_1/07_task.rb
> +first  = (1..20).collect { rand(1..30) }
виправлено

2018-11-14 20:06 UTC, slenderock requested changes
Завдання з теми "Objects" окремим реквестом! Кинь новий реквест без цих змін

2018-11-14 20:06 UTC, slenderock commented on objects/vlad.vovk/03_task.rb
> +class A
Завдання з теми "Objects" окремим реквестом! Кинь новий реквест без цих змін

2018-11-14 20:26 UTC, slenderock approved these changes

2018-11-14 20:26 UTC, merged