Homework #1
MastersAcademy/ruby-course-2018 pull request #11
Opened 2018-11-09 19:00 UTC by EugeneTymoshenko

2018-11-10 13:22 UTC, Patriarh22 commented on ruby_basic/eugene.tymoshenko/task_1.rb
> +# Скрипт приймає таймзону в виді тексту та виводить поточний час в заданій таймзоні
Потрібно взяти за правило, що коментарі в коді пишуться виключно англійською мовою

2018-11-10 13:22 UTC, Patriarh22 commented on ruby_basic/eugene.tymoshenko/task_4.rb
> +boolean = gets.chomp.eql?('true') ? true : false
Результатом виконання ```gets.chomp.eql?('true')``` і так буде булеве значення, в даному випадку тернарний оператор зайвий

2018-11-10 13:35 UTC, Patriarh22 commented on ruby_basic/eugene.tymoshenko/task_5.rb
> +  file.each_line do |line|
Тут можна обійтись без ```count```, використовуючи метод ```each_with_index```

2018-11-10 13:35 UTC, Patriarh22 commented on ruby_basic/eugene.tymoshenko/task_5.rb
> +    return puts count if line.include? string
Краще використати замість ```return``` метод ```break```, орієнтовно таким чином
```ruby
  next unless line.include?(string)
  puts count # or 'index' if you use 'each_with_index' instead 'each_line'
  break
```

2018-11-10 13:49 UTC, Patriarh22 commented on ruby_basic/eugene.tymoshenko/task_6.rb
> +    arg1/arg2
Не вистачає відступів між аргументами і методом ```/```

2018-11-12 10:54 UTC, YuriiRudenko requested changes

2018-11-12 10:54 UTC, YuriiRudenko commented on ruby_basic/eugene.tymoshenko/task_1.rb
> +  obtained_timezone = TIMEZONES.dig(timezone)
є сенс звертатись через dig тільки коли це цепочка ключів, а в даному випадку достатньо звичайного звернення до хеша

2018-11-12 10:54 UTC, YuriiRudenko commented on ruby_basic/eugene.tymoshenko/task_1.rb
> +  return "Unsupported key provided. Supported keys are: #{TIMEZONES.keys}!" if obtained_timezone.nil?
return "Unsupported key provided. Supported keys are: #{TIMEZONES.keys}!" unless obtained_timezone

2018-11-12 10:54 UTC, YuriiRudenko commented on ruby_basic/eugene.tymoshenko/task_6.rb
> +    arg1 / arg2
можуть бути проблеми з діленням двох цілих чисел 
можуть бути проблеми з діленням на нуль

2018-11-13 06:01 UTC, merged