Homework ruby basics
MastersAcademy/ruby-course-2018 pull request #13
Opened 2018-11-09 21:54 UTC by 3apy6a

2018-11-09 21:55 UTC, 3apy6a commented
1 commit

2018-11-11 16:12 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task1.rb
> +require 'date'
Це точно необхідно для виконання скріпта?

2018-11-11 16:12 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task1.rb
> +# Скрипт приймає таймзону в виді тексту та виводить поточний час в заданій таймзоні
Коментарі в коді пишуться виключно англійською мовою

2018-11-11 16:12 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task1.rb
> +  def initialize(one)
Не зрозуміло що саме приймається на вхід метода в якості аргумента, ```one``` ні про що не каже

2018-11-11 16:12 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task1.rb
> +timezona = Timezones.new(ARGV[0])
Створювати інстанс класу варто після перевірки на валідність вхідних параметрів, а не перед перевіркою

2018-11-11 16:12 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task1.rb
> +if timezona.respond_to?(ARGV[0])
Слід поміщати значення ```ARGV[0]``` в змінну, тоді не доведеться кожен раз при виклику бігати по масиву і при читанні коду стане зрозуміліше з чим саме виконуються дії

2018-11-11 16:18 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task2.rb
> +fh.each { |line| puts line }
Тут відбувається лише вивід кожного рядка, без зміни кольору згідно вхідних параметрів скріпта. Немає обробки вхідного параметру ```ARGV[0]```, куди, власне, повинен приходити колір.

2018-11-11 16:38 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task4.rb
> +# Скрипт приймає boolean, перетворює його в integer, в string,
Потрібна реалізація або прибрати цей файл

2018-11-11 16:38 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task5.rb
> +    p "Number of the required line: #{index}"
Тут відбувається вивід індекса, а не номеру рядка

2018-11-11 16:38 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task5.rb
> +text.each_with_index do |line, index|
Потрібно вивести номер рядка з файлу, де ВПЕРШЕ зустрічається заданий рядок, цей скріпт виведе всі співпадіння

2018-11-11 16:46 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task6.rb
> +if ARGV.length != 3
Перевірка на кількість вхідних параметрів повинна бути перед створенням інстансу

2018-11-11 16:46 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task6.rb
> +arif = Numbers.new(ARGV[0], ARGV[1])
Потрібно сетить ```ARGV``` в змінні

2018-11-11 16:46 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/task6.rb
> +  def initialize(one, two)
Не зрозуміло, що метод приймає в якості вхідних параметрів, потрібно назвати їх зрозуміліше

2018-11-11 16:51 UTC, Patriarh22 commented on ruby_basic/oleksandr.zaruba/timezone.rb
> +# Скрипт приймає таймзону в виді тексту та виводить поточний час в заданій таймзоні
Дуже схоже на task1.rb, схоже, зайвий файл

2018-11-11 17:09 UTC, 3apy6a commented
Дякую, зараз сяду працювати, над зауваженнями. Фаіл timezone.rb схожий по
реалізації на task1, захотів зробити не на 5 тайм зон. як в завданні. от і
добавив в інший файл. наступного разу не буду лишні файли пушити. Ще раз
дякую за ваш час.

2018-11-11 20:59 UTC, YuriiRudenko requested changes

2018-11-11 20:59 UTC, YuriiRudenko commented on ruby_basic/oleksandr.zaruba/task1.rb
> +require 'date'
цей модуль не треба, так як використовується виключно unix функції для отримання часу

2018-11-11 21:01 UTC, YuriiRudenko commented
> Дякую, зараз сяду працювати, над зауваженнями. Фаіл timezone.rb схожий по реалізації на task1, захотів зробити не на 5 тайм зон. як в завданні. от і добавив в інший файл. наступного разу не буду лишні файли пушити. Ще раз дякую за ваш час.

Кілька рішень однієї задачі - це просто прекрасно, варто лише називати файли трохи інакше, типу timezone_solution2.rb

2018-11-15 18:14 UTC, YuriiRudenko commented on ruby_basic/oleksandr.zaruba/task8.rb
> +p 'Enter array what include 10 elements'
недобре обмежувати інпут

2018-11-15 18:14 UTC, merged