Home Work #2
MastersAcademy/ruby-course-2018 pull request #17
Opened 2018-11-15 13:35 UTC by st3p

2018-11-19 11:50 UTC, YuriiRudenko requested changes

2018-11-19 11:50 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/mario_game.rb
> +  attr_accessor :level_background, :count_of_enemies, :speed_enemies, :level_number
це теж можна винести в модуль

2018-11-19 11:50 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/mario_game.rb
> +    if ObjectSpace.each_object(self.class).count >= FINAL_LEVEL
в ```initialize``` повинна бути лише ініціалізація даних, не логіка

2018-11-19 11:50 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/mario_game.rb
> +    @level_number = level_number
з приводу питання по винесенню ініціалізатора: можна зробити метод, який викликається в обох ініціалізаторах, а сам метод винести в модуль

2018-11-19 11:50 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task8.rb
> +    @arr = []
можна так
```ruby
@arr = File.readlines(level).map(&:chars)
```

2018-11-19 11:50 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task8.rb
> +class Game
Як гру правильно запускати? Вічний цикл кладе наглухо систему

2018-11-19 11:50 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task7.rb
> +        ")" => "(",
подвійні лапки використовуєм тільки якщо всередині інтерполяція буде

2018-11-19 11:50 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task5.rb
> +      :black => 30,
```ruby
black: 30,
```

2018-11-19 13:23 UTC, tte18 commented on objects/vazgen.bakhchagulian/mario_game.rb
> +  attr_accessor :level_background, :count_of_enemies, :speed_enemies, :level_number
Виправив

2018-11-19 13:23 UTC, tte18 commented on objects/vazgen.bakhchagulian/mario_game.rb
> +    if ObjectSpace.each_object(self.class).count >= FINAL_LEVEL
Виправив

2018-11-19 13:23 UTC, tte18 commented on objects/vazgen.bakhchagulian/mario_game.rb
> +    @level_number = level_number
Виправив

2018-11-19 13:23 UTC, tte18 commented on objects/vazgen.bakhchagulian/task8.rb
> +    @arr = []
Виправив

2018-11-19 13:23 UTC, tte18 commented on objects/vazgen.bakhchagulian/task7.rb
> +        ")" => "(",
Виправив

2018-11-19 13:23 UTC, tte18 commented on objects/vazgen.bakhchagulian/task5.rb
> +      :black => 30,
Виправив

2018-11-20 15:33 UTC, YuriiRudenko requested changes

2018-11-20 15:33 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task7.rb
> +    return stack.empty?
```return``` не потрібен, якщо ```return``` немає, метод завжди повертає останній рядок

2018-11-20 15:33 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task7.rb
> +        if !stack.empty?
```ruby
top_element = stack.present? ? stack.pop : '#'
```

2018-11-20 15:33 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task7.rb
> +    self.each_char do |char|
```self``` не обовязковий

2018-11-20 15:33 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task7.rb
> +    mapping = {
ці дані не міняються, винеси в константу

2018-11-20 15:33 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task5.rb
> +  color_codes = {
це повинна бути константа, а не змінна

2018-11-20 15:33 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task4+6.rb
> +  operators = {
це повинна бути константа, а не змінна

2018-11-20 15:33 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task3.rb
> +    even_numbers = []
можна простіше і менше
```ruby
def even_numbers
    select { |f| f % 2 == 0 }
end
```

2018-11-20 15:33 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/mario_game.rb
> +  def on_final_level?
якщо в кінці методу ```?``` то він повинен вертати ```true``` або ```false```

2018-11-20 21:09 UTC, st3p commented on objects/vazgen.bakhchagulian/task7.rb
> +    mapping = {
Виправив усе, крім цього. Щоб винести в константу, доведеться винести її в сам модуль, а не метод, а це означає, що константа буде виділена навіть якщо метод не викликали

2018-11-21 12:58 UTC, YuriiRudenko requested changes

2018-11-21 12:58 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/mario_game.rb
> +  attr_accessor :level_background, :count_of_enemies, :speed_enemies, :level_number
аксесори є, але вони ніде не використовуються

2018-11-21 12:58 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task3.rb
> +class Array
можна так
```ruby
Array.include EvenNumbers
```

2018-11-21 12:58 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task4+6.rb
> +  OPERATORS = {
ФРІЗИМ константи

2018-11-21 12:58 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task4+6.rb
> +puts "\e[#{COLOR_CODES.sample}m#{MyNum.new(ARGV[0].to_f,ARGV[1].to_f).send(ARGV[2].downcase.to_sym)}\e[0m"
не варто робити код НАСТІЛЬКИ нечитабельним

2018-11-21 12:58 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task7.rb
> +module Brackets
```ruby
ruby 1.rb '{{aaa}}'
#=> invalid
```

2018-11-21 17:32 UTC, st3p commented on objects/vazgen.bakhchagulian/task7.rb
> +module Brackets
Виправив усе

2018-11-21 18:11 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task7.rb
> +  MAPPING = {
не зафрізив

2018-11-21 18:11 UTC, YuriiRudenko commented on objects/vazgen.bakhchagulian/task7.rb
> +puts ARGV[0].gsub(/\w*\s*/, '').parentheses_valid? ? "valid" : "invalid"
``` ? "valid" : "invalid"``` краще перенести всередину метода

2018-11-21 18:11 UTC, YuriiRudenko approved these changes

2018-11-21 18:12 UTC, merged