Homework_2. Complited 1-6 tasks
MastersAcademy/ruby-course-2018 pull request #18
Opened 2018-11-15 20:15 UTC by vladvovk2

2018-11-15 21:40 UTC, slenderock requested changes
Декілька пропозицій по покращеннях шукай в коментарях

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/06_task.rb
> +    colors = Colorize::COLORS
можна замінити на просто `Colorize::COLORS.values.sample`

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/01_task.rb
> +  attr_accessor :toad_health, :toad_strength, :toad_speed
якщо описав гетери і сетери то юзай їх. В тебе скрізь звернення до @ замість цього

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/01_task.rb
> +  def initialize(toad_health: 0,
Твоє рішення опису дефолтних значень найкраще з очевидних, але я підозрюю що можна щось краще придумать, наприклад:
```
....
INITIAL_OPTIONS = { 
  toad_health: 0,
  toad_speed: 0,
  toad_strength: 0,
  level_background: 0,
  count_of_enemies: 0,
  speed_enemies: 0,
  level_number: 0
}.freeze
 def initialize(INITIAL_OPTIONS)
...
```

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/01_task.rb
> +    "Toad health is: #{@toad_health}"
використай геттер

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/01_task.rb
> +    "Toad speed is: #{@toad_speed}"
використай геттер

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/01_task.rb
> +    "Toad strength is: #{@toad_strength}"
використай геттер

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/game_constructor.rb
> +    @level_number = new_level_number
використай сеттер

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/game_constructor.rb
> +    @background = new_background_color
використай сеттер

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/game_constructor.rb
> +    @speed_enemies = new_speed_enemies
використай сеттер

2018-11-15 21:40 UTC, slenderock commented on objects/vlad.vovk/game_constructor.rb
> +    @speed_enemies = new_speed_enemies
ну кароч і скрізь

2018-11-15 21:50 UTC, slenderock commented on objects/vlad.vovk/game_constructor.rb
> +class GameConstructor
це має буть модуль, зараз валиться помилка

2018-11-15 21:54 UTC, slenderock requested changes

2018-11-15 21:54 UTC, slenderock commented on objects/vlad.vovk/game_constructor.rb
> +  attr_accessor :level_background, :count_of_enemies, :speed_enemies, :level_number
Отут трішки нерозбериха виходить, атрибути називаються по одному, а гетери для них оголошені з іншими назвами. До речі по суті тут сеттери не потрібні, так як замість сетерів використовуються кастомні методи

2018-11-15 22:09 UTC, slenderock requested changes

2018-11-15 22:09 UTC, slenderock commented on objects/vlad.vovk/02_task.rb
> +    last_level if ObjectSpace.each_object(self.class).count == LAST_LEVEL
довгі кондішени, які не можна прочитати візуально краще виносити в окремі методи, в такому разі код буде краще читатись. В ідеалі зводити все ледь не до речень на англійській мові
```
print greeting_message if last_level_reached?
```

2018-11-15 22:09 UTC, slenderock commented on objects/vlad.vovk/colorize.rb
> +      colorize(text, value)
тут не вистачає `puts`

2018-11-15 22:11 UTC, slenderock commented on objects/vlad.vovk/game_constructor.rb
> +    "Count of enemies on level is: #{@enemies}"
тут використай геттери скрізь

2018-11-15 22:13 UTC, slenderock commented on objects/vlad.vovk/03_task.rb
> +  def self.even_number(array)
назва методу не відповідає результату який повертається. має бути в множині

2018-11-15 22:16 UTC, slenderock commented on objects/vlad.vovk/05_task.rb
> +  COLORS = {
давай по DRY

сюди теж просто include-ом

2018-11-16 20:39 UTC, vladvovk2 commented on objects/vlad.vovk/03_task.rb
> +  def self.even_number(array)
Виправив + додав видалення 0 та перевірку стрінга

2018-11-16 20:41 UTC, vladvovk2 commented on objects/vlad.vovk/05_task.rb
> +  COLORS = {
Виправив.

2018-11-16 20:41 UTC, vladvovk2 commented on objects/vlad.vovk/colorize.rb
> +      colorize(text, value)
Виправив.

2018-11-16 20:46 UTC, vladvovk2 commented on objects/vlad.vovk/02_task.rb
> +    last_level if ObjectSpace.each_object(self.class).count == LAST_LEVEL
Виправив. Дякую за пораду.

2018-11-16 20:49 UTC, vladvovk2 commented on objects/vlad.vovk/game_constructor.rb
> +class GameConstructor
Не замітив цього =_=
Просто всі задачі, через зручність перевірки, роблю на repl.it і попросту не пофіксив це, томущо дана повилка виникала)

2018-11-16 20:50 UTC, vladvovk2 commented on objects/vlad.vovk/06_task.rb
> +    colors = Colorize::COLORS
Виправив.

2018-11-16 21:15 UTC, vladvovk2 commented on objects/vlad.vovk/01_task.rb
> +  attr_accessor :toad_health, :toad_strength, :toad_speed
Виправив.

2018-11-16 21:15 UTC, vladvovk2 commented on objects/vlad.vovk/01_task.rb
> +    "Toad health is: #{@toad_health}"
Виправив.

2018-11-16 21:15 UTC, vladvovk2 commented on objects/vlad.vovk/01_task.rb
> +    "Toad speed is: #{@toad_speed}"
Виправив.

2018-11-16 21:15 UTC, vladvovk2 commented on objects/vlad.vovk/01_task.rb
> +    "Toad strength is: #{@toad_strength}"
Виправив.

2018-11-16 21:15 UTC, vladvovk2 commented on objects/vlad.vovk/game_constructor.rb
> +  attr_accessor :level_background, :count_of_enemies, :speed_enemies, :level_number
Виправив.

2018-11-16 21:18 UTC, vladvovk2 commented on objects/vlad.vovk/game_constructor.rb
> +    "Count of enemies on level is: #{@enemies}"
Виправив.

2018-11-17 19:50 UTC, slenderock requested changes
Одна порада, все інше гуд

2018-11-17 19:50 UTC, slenderock commented on objects/vlad.vovk/03_task.rb
> +  def self.even_numbers(array)
Ця умова виглядає не читабельно та дещо з умов взаємоабсурдно. Наприклад, ти перевіряєш чи число символ, а потом перевіряєш чи інтежер. Умова на просто інтежер вже б не дала true, а як наслідок умова з символом не потрібна
Згідно нового уточнення, числа будуть приходити в необхідному форматі, тому не потрібно їх конвертувати в #to_i
Давай спростимо до простого `i.is_a?(Integer) && i.even?`

2018-11-17 19:51 UTC, slenderock commented on objects/vlad.vovk/03_task.rb
> +  def self.even_numbers(array)
ну і так як в нас умова стала невеличкою, переїдемо на {} для блоку

2018-11-18 09:21 UTC, slenderock commented on objects/vlad.vovk/03_task.rb
> +  def self.even_numbers(array)
@vladvovk2 пофікси це і я замержу. Там фікс швидкий має бути

2018-11-18 11:30 UTC, vladvovk2 commented on objects/vlad.vovk/03_task.rb
> +  def self.even_numbers(array)
Пофіксив, перевіряй. Дякую за поради, дуже гарно допомагають, що аж самому починає приємно дивитись на код :)

2018-11-21 10:10 UTC, slenderock approved these changes

2018-11-21 10:10 UTC, merged