All done
MastersAcademy/ruby-course-2018 pull request #2
Opened 2018-11-07 23:12 UTC by st3p

2018-11-08 11:57 UTC, YuriiRudenko requested changes

2018-11-08 11:57 UTC, YuriiRudenko commented on ruby_basic/vazgen.bakhchagulian/task1.rb
> +puts Time.now.utc + ARGV[0].downcase.sub(/utc/, '').to_i * 3600
яким чином виконати цей скрипт?

2018-11-08 11:57 UTC, YuriiRudenko commented on ruby_basic/vazgen.bakhchagulian/task2.rb
> +    "black" => 30,
якщо немає складних ключів, то краще їх задавати як symbol
red: 31,

2018-11-08 11:57 UTC, YuriiRudenko commented on ruby_basic/vazgen.bakhchagulian/task4.rb
> +puts (1==1).to_i
Задача була отримувати boolean з консолі

2018-11-08 11:57 UTC, YuriiRudenko commented on ruby_basic/vazgen.bakhchagulian/task5.rb
> +    if line.chomp == str
це спрацює тільки при повному співпадінні, а треба, щоб виводило номер, якщо запитаний рядок ХОЧА Б ВХОДИТЬ в рядок з файла

2018-11-08 11:57 UTC, YuriiRudenko commented on ruby_basic/vazgen.bakhchagulian/task6.rb
> +  puts eval(ARGV[0]+@methods[ARGV[2]]+ARGV[1])
ніколи не юзайте eval

2018-11-08 11:57 UTC, YuriiRudenko commented on ruby_basic/vazgen.bakhchagulian/task7.rb
> +  puts a.split("").sample
без необхідності не юзайте подвійні лапки

2018-11-08 12:14 UTC, slenderock requested changes

2018-11-08 12:14 UTC, slenderock commented on ruby_basic/vazgen.bakhchagulian/task6.rb
> +  @methods = {
це має бути константа замість інстанса

2018-11-09 10:31 UTC, st3p commented on ruby_basic/vazgen.bakhchagulian/task1.rb
> +puts Time.now.utc + ARGV[0].downcase.sub(/utc/, '').to_i * 3600
виправлено

2018-11-09 10:32 UTC, st3p commented on ruby_basic/vazgen.bakhchagulian/task2.rb
> +    "black" => 30,
виправлено

2018-11-09 10:32 UTC, st3p commented on ruby_basic/vazgen.bakhchagulian/task4.rb
> +puts (1==1).to_i
виправлено

2018-11-09 10:32 UTC, st3p commented on ruby_basic/vazgen.bakhchagulian/task5.rb
> +    if line.chomp == str
виправлено

2018-11-09 10:32 UTC, st3p commented on ruby_basic/vazgen.bakhchagulian/task7.rb
> +  puts a.split("").sample
виправлено

2018-11-09 10:32 UTC, st3p commented on ruby_basic/vazgen.bakhchagulian/task6.rb
> +  puts eval(ARGV[0]+@methods[ARGV[2]]+ARGV[1])
виправлено

2018-11-09 10:32 UTC, st3p commented on ruby_basic/vazgen.bakhchagulian/task6.rb
> +  @methods = {
виправлено

2018-11-09 11:07 UTC, slenderock approved these changes

2018-11-13 08:20 UTC, merged