Homework #2 Vlad Metelap
MastersAcademy/ruby-course-2018 pull request #21
Opened 2018-11-16 12:46 UTC by westnick2

2018-11-18 16:05 UTC, Patriarh22 commented on objects/vlad.metelap/extramodule.rb
> +    puts "Count of enemies on level is: #{@background}"
Смисл повідомлення не відповідає назві методу

2018-11-18 16:05 UTC, Patriarh22 commented on objects/vlad.metelap/cheesegame.rb
> +  attr_accessor :level_background, :count_of_enemies, :speed_enemies, :level_number
Ексесори спільні для класів ```Cheesegame``` і ```MarioGame```, їх можна винести в модуль

2018-11-18 16:05 UTC, Patriarh22 commented on objects/vlad.metelap/cheesegame.rb
> +# Cheesegame game
Зайвий коментар, із назви класу і файлу це і так зрозуміло

2018-11-18 16:05 UTC, Patriarh22 commented on objects/vlad.metelap/mario_game.rb
> +20.times do |i|
Для однорядкових блоків потрібно використовувати ```{}```, а не конструкцію ```do ... end```

2018-11-18 16:05 UTC, Patriarh22 commented on objects/vlad.metelap/mario_game.rb
> +# Mario game
Очевидно із назви класу, зайвий коментар

2018-11-18 16:21 UTC, Patriarh22 commented on objects/vlad.metelap/cheesegame.rb
> +  include Extension
Такого модуля в пулл реквесті немає

2018-11-18 16:21 UTC, Patriarh22 commented on objects/vlad.metelap/task3.rb
> +    select_numbers = array.select { |item| item.is_a? Integer }
Ця логіка не покриває випадку коли число приходить у вигляді рядка, тобто всі значення масиву ```['2', 4, '6', 8]``` повинні повернутись як парні
Зайве проходити по масиву двічі, умова для метода ```select``` може задаватись комплексна, наприклад
```ruby
  array.select { |item| item.is_a?(Integer) && item.even? }
```

2018-11-18 16:31 UTC, Patriarh22 commented on objects/vlad.metelap/task4.rb
> +  end
task4.rb:20: syntax error, unexpected end-of-input, expecting keyword_end

2018-11-18 16:31 UTC, Patriarh22 commented on objects/vlad.metelap/task5.rb
> +  colours = {black: "black", red: "red", green: "green", blue: "blue"}.freeze
Це повинна бути константа

2018-11-18 16:31 UTC, Patriarh22 commented on objects/vlad.metelap/task5.rb
> +
Зайвий відступ

2018-11-18 16:37 UTC, Patriarh22 commented on objects/vlad.metelap/task6.rb
> +    @a, @b = a, b
Не рекомендується виконувати паралельне присвоювання, за винятком коли змінні сетяться із елементів масиву

2018-11-18 16:37 UTC, Patriarh22 commented on objects/vlad.metelap/task6.rb
> +class Maths
В цьому [завданні](https://github.com/MastersAcademy/ruby-course-2018/blob/master/objects/hometask.md#task-6-) обов'язкове використання міксінів

2018-11-18 17:14 UTC, Patriarh22 commented on objects/vlad.metelap/task7.rb
> +    arr = string.split("")
Цей шмат логіки
```ruby
  arr = string.split("")
  array_of_symbols = []
  arr.each do |x|
    array_of_symbols << x if parentheses_symbols.include? x
  end
```
краще реалізувати, використовуючи метод ```chars``` + метод ```select```

2018-11-18 17:14 UTC, Patriarh22 commented on objects/vlad.metelap/task7.rb
> +      if (array_of_symbols.count % 2).zero?
Краще використати метод ```even?```

2018-11-18 17:14 UTC, Patriarh22 commented on objects/vlad.metelap/task7.rb
> +        i = 0
потрібно логічно і зрозуміло переназвати змінні ```i```, ```c```, ```x```

2018-11-18 17:14 UTC, Patriarh22 commented on objects/vlad.metelap/task7.rb
> +        while i < array_of_symbols.count / 2
Дію ```array_of_symbols.count / 2``` потрібно винести в змінну, інакше ця операція буде відбуватись при кожній ітерації циклу

2018-11-18 17:14 UTC, Patriarh22 commented on objects/vlad.metelap/task7.rb
> +          x = array_of_symbols[c] == parentheses_pairs["#{array_of_symbols[i]}"]
```array_of_symbols[i]``` в змінну

2018-11-18 17:14 UTC, Patriarh22 commented on objects/vlad.metelap/task7.rb
> +    if parentheses_pairs.has_key?(string[0])
замість ```has_key?``` рекомендується використовувати ```key?```

2018-11-20 10:59 UTC, westnick2 commented on objects/vlad.metelap/extramodule.rb
> +    puts "Count of enemies on level is: #{@background}"
resolved

2018-11-20 11:11 UTC, westnick2 commented on objects/vlad.metelap/cheesegame.rb
> +  include Extension
виправлено

2018-11-20 11:12 UTC, westnick2 commented on objects/vlad.metelap/cheesegame.rb
> +# Cheesegame game
виправлено

2018-11-20 11:13 UTC, westnick2 commented on objects/vlad.metelap/cheesegame.rb
> +  attr_accessor :level_background, :count_of_enemies, :speed_enemies, :level_number
винесено

2018-11-20 11:13 UTC, westnick2 commented on objects/vlad.metelap/mario_game.rb
> +# Mario game
виправлено

2018-11-20 11:26 UTC, westnick2 commented on objects/vlad.metelap/mario_game.rb
> +20.times do |i|
Виправлено

2018-11-20 11:35 UTC, westnick2 commented on objects/vlad.metelap/task5.rb
> +  colours = {black: "black", red: "red", green: "green", blue: "blue"}.freeze
виправлено

2018-11-20 11:41 UTC, westnick2 commented on objects/vlad.metelap/task5.rb
> +
Чому зайвий, якщо йдуть вкладені цикли each do
define_method do ?

2018-11-20 11:42 UTC, westnick2 commented on objects/vlad.metelap/task6.rb
> +    @a, @b = a, b
Виправлено

2018-11-20 11:44 UTC, westnick2 commented on objects/vlad.metelap/task4.rb
> +  end
виправлено

2018-11-20 13:19 UTC, westnick2 commented on objects/vlad.metelap/task3.rb
> +    select_numbers = array.select { |item| item.is_a? Integer }
вже покриває

2018-11-20 13:19 UTC, westnick2 commented on objects/vlad.metelap/task5.rb
> +
виправлено

2018-11-20 15:58 UTC, westnick2 commented on objects/vlad.metelap/task6.rb
> +class Maths
реалізовано

2018-11-20 15:58 UTC, westnick2 commented on objects/vlad.metelap/task7.rb
> +    arr = string.split("")
реалізовано

2018-11-20 15:59 UTC, westnick2 commented on objects/vlad.metelap/task7.rb
> +        i = 0
resolved

2018-11-20 16:00 UTC, westnick2 commented on objects/vlad.metelap/task7.rb
> +        while i < array_of_symbols.count / 2
resolved

2018-11-20 16:01 UTC, westnick2 commented on objects/vlad.metelap/task7.rb
> +          x = array_of_symbols[c] == parentheses_pairs["#{array_of_symbols[i]}"]
resolved

2018-11-20 16:01 UTC, westnick2 commented on objects/vlad.metelap/task7.rb
> +    if parentheses_pairs.has_key?(string[0])
resolved

2018-11-20 16:04 UTC, westnick2 commented
mistakes resolved

2018-11-21 13:01 UTC, Patriarh22 requested changes

2018-11-21 13:01 UTC, Patriarh22 commented on objects/vlad.metelap/mario_game.rb
> +    puts
Мені здається, що ```puts``` тут зайвий

2018-11-21 13:01 UTC, Patriarh22 commented on objects/vlad.metelap/cheesegame.rb
> +  def initialize(level_background, count_of_enemies, speed_enemies, level_number)
Краще метод ```initialize``` розмістити перед методом ```speed```, прийнято його писати на початку класу

2018-11-21 13:01 UTC, Patriarh22 commented on objects/vlad.metelap/task3.rb
> +    select_numbers = array.select { |item| item.to_i.even? if ((item.is_a? (Integer)) || (item.is_a?(String))) }
В метод ```select``` завжди передається блок із умовою вибірки елементів. ```if``` тут зайвий, достатньо перечислити всі умови через ```&&``` або ```||```. Доречі, не повинно бути відступів між методом і дужками з аргументом

2018-11-21 13:01 UTC, Patriarh22 commented on objects/vlad.metelap/task3.rb
> +arr = ['2', 4, '6', 8, '12', 0]
Для достовірності скріпта, додай непарні елементи в масив, в тому числі у вигляді рядків

2018-11-21 13:01 UTC, Patriarh22 commented on objects/vlad.metelap/task5.rb
> +class String
Потрібно винести клас String в окремий файл і виконати ```require``` тут

2018-11-21 13:01 UTC, Patriarh22 commented on objects/vlad.metelap/task6.rb
> +      # "\e[#{colour}m#{rezult}\e[0m"
Прибирай зайвий код

2018-11-21 13:01 UTC, Patriarh22 commented on objects/vlad.metelap/task6.rb
> +class String
Якщо клас ```String``` винесений в окремий файл, то його можна зарекваірить і сюди

2018-11-21 13:01 UTC, Patriarh22 commented on objects/vlad.metelap/task7.rb
> +      array_of_symbols = arr.select {|x| parentheses_symbols.include? x}
Можна обійтися без змінної  ```arr ``` ось так```string.chars.select {|x| parentheses_symbols.include? x}```, тільки змінна ```x``` ні про що не каже, потрібно осмислено називати змінні

2018-11-22 06:36 UTC, westnick2 commented on objects/vlad.metelap/cheesegame.rb
> +  def initialize(level_background, count_of_enemies, speed_enemies, level_number)
resolved

2018-11-22 06:38 UTC, westnick2 commented on objects/vlad.metelap/mario_game.rb
> +    puts
resolved

2018-11-22 06:47 UTC, westnick2 commented on objects/vlad.metelap/task3.rb
> +    select_numbers = array.select { |item| item.to_i.even? if ((item.is_a? (Integer)) || (item.is_a?(String))) }
resolved

2018-11-22 06:47 UTC, westnick2 commented on objects/vlad.metelap/task3.rb
> +arr = ['2', 4, '6', 8, '12', 0]
resolved

2018-11-22 06:54 UTC, westnick2 commented on objects/vlad.metelap/task5.rb
> +class String
Дуже вдячний за зауваження! Виправив!

2018-11-22 06:55 UTC, westnick2 commented on objects/vlad.metelap/task6.rb
> +class String
виправив

2018-11-22 06:56 UTC, westnick2 commented on objects/vlad.metelap/task6.rb
> +      # "\e[#{colour}m#{rezult}\e[0m"
resolved

2018-11-22 07:01 UTC, westnick2 commented on objects/vlad.metelap/task7.rb
> +      array_of_symbols = arr.select {|x| parentheses_symbols.include? x}
resolved

2018-11-22 15:17 UTC, westnick2 commented on objects/vlad.metelap/task7.rb
> +      if (array_of_symbols.count % 2).zero?
resolved

2018-11-23 20:46 UTC, Patriarh22 requested changes

2018-11-23 20:46 UTC, Patriarh22 commented on objects/vlad.metelap/task3.rb
> +    array.select {|item| (item.to_i.even?) && ((item.is_a? (Integer)) || (item.is_a?(String)))}
Ти приводиш значення до типу Integer, перевіряєш чи воно парне, а потім перевіряєш тип вхідного значення.  Незрозуміло, яке логічне навантаження виконує ось ця частина ```((item.is_a? (Integer)) || (item.is_a?(String)))```. Якщо і робити перевірку на тип (якщо це потрібно), то перед виконанням дій із вхідним значенням. Ще раз нагадую, не потрібно робити відступи між методом і аргументом, що в нього передається, забагато дужок, вони зайві, достатньо було б ```item.to_i.even? && (item.is_a?(Integer) || item.is_a(String))```.

2018-11-26 07:24 UTC, westnick2 commented on objects/vlad.metelap/task3.rb
> +    array.select {|item| (item.to_i.even?) && ((item.is_a? (Integer)) || (item.is_a?(String)))}
Вирішив спочатку привести до типу цілих, а потім здійснити перевірку на парність. Відступи прибрав.

2018-11-26 08:32 UTC, merged