hw2 1-4, hw1 fix 3-8 Перезалив
MastersAcademy/ruby-course-2018 pull request #22
Opened 2018-11-16 18:39 UTC by VladZelenko

2018-11-17 12:48 UTC, YuriiRudenko requested changes

2018-11-17 12:48 UTC, YuriiRudenko commented on objects/vlad.zelenko/task1/new_game.rb
> +require_relative "output_methods"
достатньо ```require```

2018-11-17 12:48 UTC, YuriiRudenko commented on objects/vlad.zelenko/task1/new_mario_game.rb
> +require_relative "../../mario_game"
require

2018-11-17 12:48 UTC, YuriiRudenko commented on objects/vlad.zelenko/task1/new_mario_game.rb
> +require_relative "output_methods"
require

2018-11-17 12:48 UTC, YuriiRudenko commented on ruby_basic/vlad.zelenko/hw1/task4.rb
> +puts "String #{str} => #{str.bytesize()}"
якщо аргументи не передаються, то можна не писати ()

2018-11-17 12:48 UTC, YuriiRudenko commented on ruby_basic/vlad.zelenko/hw1/task4.rb
> +numb = bool_1 == true ? 1 : 0
numb = bool ? 1 : 0

2018-11-17 12:48 UTC, YuriiRudenko commented on objects/vlad.zelenko/task4/dynamic_math.rb
> +    @num_1 = num_1
іменування змінних повинно бути осмисленим

2018-11-17 12:48 UTC, YuriiRudenko commented on objects/vlad.zelenko/task4/dynamic_math.rb
> +      @num_1.send(operator.to_sym, @num_2)
все ускладнюється правилами ділення при 0

2018-11-17 12:48 UTC, YuriiRudenko commented on objects/vlad.zelenko/task3/even_numb.rb
> +    @arr.each { |x| puts x if x.is_a?(Numeric) && x.even? }
треба не відсіювати рядки, а перетворити в числа
можна в ініціалізаторі написати
```ruby
@arr = arr.map(&:to_f)
```
тоді в методі
```ruby
puts @arr.select(&:even?)
```

2018-11-17 12:48 UTC, YuriiRudenko commented on objects/vlad.zelenko/task3/even_numb.rb
> +even_numb = EvenNumb.new([0, 1, 2, 3, 4, "two", "seven", 5, 6, 8, 9])
в задачі малось на квазі числа типу '1', 1, '1.3', 1.3

2018-11-17 12:48 UTC, YuriiRudenko commented on objects/vlad.zelenko/task2/new_mario_game.rb
> +  def you_win
я так розумію, це ще не готове?

2018-11-18 19:25 UTC, VladZelenko commented on objects/vlad.zelenko/task1/new_game.rb
> +require_relative "output_methods"
виправив

2018-11-18 19:26 UTC, VladZelenko commented on ruby_basic/vlad.zelenko/hw1/task4.rb
> +puts "String #{str} => #{str.bytesize()}"
виправив

2018-11-18 19:27 UTC, VladZelenko commented on objects/vlad.zelenko/task1/new_mario_game.rb
> +require_relative "output_methods"
виправив

2018-11-18 19:27 UTC, VladZelenko commented on objects/vlad.zelenko/task1/new_mario_game.rb
> +require_relative "../../mario_game"
виправив

2018-11-18 19:29 UTC, VladZelenko commented on ruby_basic/vlad.zelenko/hw1/task4.rb
> +numb = bool_1 == true ? 1 : 0
виправив

2018-11-18 19:35 UTC, VladZelenko commented on objects/vlad.zelenko/task4/dynamic_math.rb
> +    @num_1 = num_1
виправив

2018-11-19 11:08 UTC, YuriiRudenko commented on objects/vlad.zelenko/task1/new_game.rb
> +require_relative "output_methods"
де?

2018-11-19 11:08 UTC, YuriiRudenko commented on ruby_basic/vlad.zelenko/hw1/task4.rb
> +numb = bool_1 == true ? 1 : 0
ну мабуть нічого не запушив

2018-11-20 15:39 UTC, YuriiRudenko commented on objects/vlad.zelenko/task1/new_mario_game.rb
> +require "output_methods"
одинарні лапки

2018-11-20 15:39 UTC, YuriiRudenko commented on objects/vlad.zelenko/task4/dynamic_math.rb
> +      "Cannot be divided by 0"
одинарні

2018-11-20 15:39 UTC, YuriiRudenko commented on ruby_basic/vlad.zelenko/hw1/task4.rb
> +arr = ARGV
логічніше було б ```arr = ARGV.first```

2018-11-20 15:39 UTC, YuriiRudenko commented on ruby_basic/vlad.zelenko/hw1/task5.rb
> +      file = file.map { |x| x.chomp}
```ruby
file.map(&:chomp).index(@text) + 1
```

2018-11-20 15:39 UTC, YuriiRudenko commented on ruby_basic/vlad.zelenko/hw1/task8.rb
> +p ARGV.map { |x| x.to_i }.sort.reverse
p ARGV.map(&:to_i).sort.reverse

2018-11-20 15:39 UTC, YuriiRudenko approved these changes

2018-11-20 15:40 UTC, merged