Homework #2
MastersAcademy/ruby-course-2018 pull request #23
Opened 2018-11-16 21:03 UTC by EugeneTymoshenko

2018-11-17 21:29 UTC, slenderock requested changes

2018-11-17 21:29 UTC, slenderock commented on objects/eugene.tymoshenko/game_actions.rb
> +    "Count of enemies on level is: #{@enemies}"
Давай в цьому модулі де можливо заюзаємо геттери)

2018-11-17 21:29 UTC, slenderock commented on objects/eugene.tymoshenko/math_operations.rb
> +    "\e[#{random_color}m#{@arg1 + @arg2}\e[0m"
якщо ти поописував скрізь аттр_акцесор, то викорситовуй описані геттери і сеттери

2018-11-17 21:29 UTC, slenderock commented on objects/eugene.tymoshenko/task_1.rb
> +require './game_actions'
почитай про різницю між require, require_relative та load

Тут краще використати require_relative 'game_actions', адже при зміні контексту виклику скрипта, падає помилка

В інших місцях те ж саме

2018-11-17 21:29 UTC, slenderock commented on objects/eugene.tymoshenko/game_actions.rb
> +    "Count of enemies on level is: #{@enemies}"
коли перейдеш на геттери та сетери, помітиш що ти поробив опечатки в оголошенні деяких аксесорів

2018-11-17 21:29 UTC, slenderock commented on objects/eugene.tymoshenko/task_2.rb
> +p b.local_variable_get(:mario7).final_game_notice rescue p 'No such method'
тут досить зробити rescue тільки для NoMethodError

2018-11-17 21:29 UTC, slenderock commented on objects/eugene.tymoshenko/task_2.rb
> +p b.local_variable_get(:mario7).final_game_notice rescue p 'No such method'
не звикай писати `rescue` без вказання помилки яку ти уникаєш

2018-11-17 21:29 UTC, slenderock commented on objects/eugene.tymoshenko/task_2.rb
> +      last_2_objects.last.define_singleton_method :final_game_notice, -> { "last level reached. Last level: #{@id}" }
геттер `attr_reader :id` описав, але не використовуєш

2018-11-17 22:16 UTC, slenderock commented
Ще одне зрозумів. В тебе в того маріо доданий рідер на @id, але в модулі є звернення до атрибуту @level_number . Через це виходить що ти робиш модуль не валідним для цього завдання, проте є можливість зробити валідним, якщо використовувати @level_number як @id, попердньо вимкнувши можливість модифікувати його ззовні(щоб не ламати описану логіку)

2018-11-18 13:22 UTC, sunstoryx commented on objects/eugene.tymoshenko/math_operations.rb
> +    "\e[#{random_color}m#{@arg1 + @arg2}\e[0m"
Привіт! Це модуль для таски 6 і я там не використовую аттр_акцесор

2018-11-18 21:23 UTC, slenderock requested changes

2018-11-18 21:23 UTC, slenderock commented on objects/eugene.tymoshenko/task_2.rb
> +    @level_number         = ObjectSpace.each_object(MarioGame).count
старайся притримуватись одного стилю коду. Ти скрізь використав сеттери, а в одному випадку через інстанс записав атрибут. Давай скрізь через сеттери :)
А якщо ти не хочеш щоб цей атрибут можна було модифікувати ззовні, опиши його в private

2018-11-19 12:18 UTC, slenderock approved these changes
cool

2018-11-19 12:19 UTC, merged