Homework 2
MastersAcademy/ruby-course-2018 pull request #28
Opened 2018-11-17 21:12 UTC by daglus

Залил пока обязательные первые две задачи, и постараюсь сегодня-завтра еще сделать что-то из остальных и поправить то что будет по замечаниях.

2018-11-17 22:12 UTC, slenderock requested changes

2018-11-17 22:12 UTC, slenderock commented on objects/nikolay.braslavets/task_1/mario_game.rb
> +
в класі не має бути описано ось це все 
```
level_background, count_of_enemies, speed_enemies, level_number = 1, 3, 45, 1
   puts "New game start in background lvl #{level_background}, and lvl game #{level_number}"
  sleep 1
  puts "Eniemies on level #{count_of_enemies}, his speed #{speed_enemies} mPh"
  sleep 1
  puts "Im gome"
```
Винеси його з класу, і звертайся до всього в контексті обєкта

2018-11-17 22:12 UTC, slenderock commented on objects/nikolay.braslavets/task_1/mario_game.rb
> +  attr_accessor(
Я бачу що ти хотів зробить гарненько, але мені не дуже подобається((
Хіба ось так:
```
attr_accessor :level_background,
              :count_of_enemies,
              :speed_enemies,
              :level_number
```

2018-11-17 22:12 UTC, slenderock commented on objects/nikolay.braslavets/task_1/game.rb
> +      @level_number = new_level_number
в тебе там описано багацько гетерів та сеттерів, давай де зможеш використай їх

2018-11-17 22:12 UTC, slenderock commented on objects/nikolay.braslavets/task_1/mortal_vombat.rb
> +MortalVombat.new.vombat_start
В класі не має бути нічого крім методів, констант і всіляких аттр_аксесорів
Все інше за межі класу

2018-11-17 22:12 UTC, slenderock commented on objects/nikolay.braslavets/task_1/mortal_vombat.rb
> +    unless angry || count_of_enemies == 0
Використай ось це замість перевірки на нуль `count_of_enemies.zero?`

2018-11-17 22:12 UTC, slenderock commented on objects/nikolay.braslavets/task_1/mortal_vombat.rb
> +  level_number, count_of_enemies, angry = 1, 0, 0
наружу його

2018-11-17 22:12 UTC, slenderock commented on objects/nikolay.braslavets/task_2/task_2.rb
> +  def final_level?
метод зі знаком питання має повертати результат в вигляді `true/false` в тебе ж він такій умові не відповідає

2018-11-18 18:13 UTC, daglus commented on objects/nikolay.braslavets/task_1/mario_game.rb
> +  attr_accessor(
Правлю. Гуглил решение, как сократить длинную строку в аццессорах, это по стайл гайду не красиво, или несет в себе еще какие-то подводные камни?

2018-11-18 18:17 UTC, daglus commented on objects/nikolay.braslavets/task_1/mortal_vombat.rb
> +    unless angry || count_of_enemies == 0
Я когда делал, смотрел  на этот метод. Но не понял как его использовать, он возвращает true/false, и если я его использовал внутри метода, интерпретатор ругался на то что он ему не известен

2018-11-18 20:56 UTC, slenderock commented on objects/nikolay.braslavets/task_1/mario_game.rb
> +  attr_accessor(
рубі при виклику будь якого методу прийнято уникати написання дужок

наприклад
```
# GOOD
p 'test'

# BAD
p('test')
```

2018-11-18 20:56 UTC, slenderock commented on objects/nikolay.braslavets/task_1/mario_game.rb
> +  attr_accessor(
Тільки некрасиво

2018-11-18 20:57 UTC, slenderock commented on objects/nikolay.braslavets/task_1/mortal_vombat.rb
> +    unless angry || count_of_enemies == 0
цей метод еквівалентний виразу `count_of_enemies == 0`

Він перевіряє чи даний аргумент є нулем

2018-11-20 12:31 UTC, daglus commented on objects/nikolay.braslavets/task_2/task_2.rb
> +  def final_level?
Затупил, исправил

2018-11-20 12:32 UTC, daglus commented on objects/nikolay.braslavets/task_1/mortal_vombat.rb
> +    unless angry || count_of_enemies == 0
Немного затупил, и он работал только если обращаться не к свойству, а к переменной через @

2018-11-21 10:01 UTC, slenderock commented
З геттерами та сеттерами в тебе там досі не пофікшено. Щось не виходить?

2018-11-21 10:26 UTC, daglus commented
Тогда, я походу не понял что нужно сделать было. Был уверен что понял верно и сделал

2018-11-21 11:03 UTC, slenderock commented
Дивись, в рубі є таке поняття як інстанс змінна(зміннна обєкту). Її особливість в тому що її областю видимості є обєкт. Такі змінні зазвичай використовують як атрибути класу. Тобто наприклад
```
class SomeClass
  def initialize(argument_1)
    @attribute_1 = argument_1
  end
  def some_other_method
     @attribute_1
  end
end
```
Виходить що в цього класу буде один атрибут(або характеристика цього класу) яка буде працювати в будь якому іншому методі цього класу(і не доступна ззовні). 
Іноді виникає ситуація коли модифікація атрибутів(характеристик) має бути виконана ззовні, тобто від обєкта, наприклад:
```
class User
  def initialize(name, age)
    @name = name
    @age = age
  end
end
serhii = User.new('Serhii', 23)
daglus_age = rand(1..100)
daglus = User.new('Nikolay', daglus_age)
```
Уявимо що мені треба змінити, наш вік. Але ж не добре створювати новий обєкт. Для цього нам і необхідні сеттери, тобто деякі методи які можуть модифікувати атрибут ззовні:
```
class User
  def initialize(name, age)
    @name = name
    @age = age
  end
  def age=(value)
    @age = value  
  end
end
serhii = User.new('Serhii', 23)
serhii.age = 24
daglus_age = rand(1..100)
daglus = User.new('Nikolay', daglus_age)
daglus.age = daglus_age + 1
```

Тепер виникає проблема, як нам дізнатись ззовні яким є вік, для цього існують геттери:
```
class User
  def initialize(name, age)
    @name = name
    @age = age
  end
  def age=(value)
    @age = value  
  end
  def age
    @age
  end
end
serhii = User.new('Serhii', 23)
serhii.age = 24
puts serhii.age
daglus_age = rand(1..100)
daglus = User.new('Nikolay', daglus_age)
daglus.age = daglus_age + 1
puts daglus.age
```
Так само до геттерів та сеттерів ми можемо звертатись в середині класу. Особливістю є тільки те що для сеттерів треба дописувати `self.` щоб вказати що ти звертаєшся саме до методу, а не оголошуєш локальну змінну
І якби ми говорили не про рубі, то моє пояснення на цьому мало б закінчитись, але в рубі пішли далі, і спростили цей момент за допомогою `attr_accessor`. Це метод для динамічного оголошення геттерів та сеттерів. Тобто:  
```
class User
  attr_accessor :name, :age
  def initialize(name, age)
    self.name = name
    self.age = age
  end
end
serhii = User.new('Serhii', 23)
serhii.age = 24
puts serhii.age
daglus_age = rand(1..100)
daglus = User.new('Nikolay', daglus_age)
daglus.age = daglus_age + 1
puts daglus.age
```
Ось такий код виглядає більш по рубішному

2018-11-26 20:55 UTC, merged