Changes +task 5 and 1
MastersAcademy/ruby-course-2018 pull request #30
Opened 2018-11-19 03:54 UTC by hawkprovvv

2018-11-19 11:41 UTC, YuriiRudenko requested changes

2018-11-19 11:41 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_6.rb
> +a = gets.chop.to_i
chop?

2018-11-19 11:41 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_6.rb
> +var1 = Calc.new
дані в клас бажано передавати через ініціалізатор

2018-11-19 11:41 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_5.rb
> +  if line.chomp == find
цей код провірить тільки на повне співпадіння, а треба ще на включення перевіряти

2018-11-19 11:41 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_4.rb
> +puts c.bytesize.to_s + ' byte'
так рядки дуже рідко форматуються
```ruby
puts "#{c.bytesize} byte"
```

2018-11-19 11:41 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_3.rb
> +a = Array.new(gets.chomp.split)
тут приведення не треба, ```split``` завжди повертає масив

2018-11-19 11:41 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_2.rb
> +# absent
well done)

2018-11-19 11:41 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_1.rb
> +ZONES = {
константи треба фрізить

2018-11-19 23:12 UTC, hawkprovvv commented on ruby_basic/victor.skyba/task_6.rb
> +a = gets.chop.to_i
suey )

2018-11-19 23:46 UTC, hawkprovvv commented on ruby_basic/victor.skyba/task_5.rb
> +  if line.chomp == find
Певно мова йде про метод include

2018-11-20 15:45 UTC, YuriiRudenko requested changes

2018-11-20 15:45 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_1.rb
> +  return "Choose from #{ZONES.keys.to_s}!" unless settled_time #так і не зрозумів, як ключі хеша можна вивести не через масив
```to_s``` не потрібен, при інтерполяції все приводиться до стрінга

2018-11-20 15:45 UTC, YuriiRudenko commented on ruby_basic/victor.skyba/task_5.rb
> +  if line.chomp value.include?
це робити не буде

2018-11-27 15:31 UTC, hawkprovvv commented on ruby_basic/victor.skyba/task_5.rb
> +  if line.chomp value.include?
пофіксив

2018-11-29 11:09 UTC, YuriiRudenko approved these changes

2018-11-29 11:09 UTC, merged