Homework2 Tasks 4, 5 and 6
MastersAcademy/ruby-course-2018 pull request #31
Opened 2018-11-23 15:17 UTC by doroshenko-e

2018-11-24 13:16 UTC, Patriarh22 requested changes

2018-11-24 13:16 UTC, Patriarh22 commented on objects/eugene.doroshenko/task4_6.rb
> +  attr_accessor :el1, :el2
Тут відбувається створення методів геттерів і сеттерів, наприклад для ```el1```
```ruby
  def el1
    @el1
  end
  
  def el1=(value)
    @el1=value
  end
```
Але в коді ці методи не використовуються, ти напряму працюєш через інстансні змінні ```@el1``` i ```@el2```, створення ексесорів тут зайве. Тому їх потрібно або прибрати, або використати в коді

2018-11-24 13:16 UTC, Patriarh22 commented on objects/eugene.doroshenko/task5.rb
> +    raise "there's no such color in hash" if color_present? == false
Зайве явно порівнювати результат викнання метду із значенням ```false```, краще зробити так ```unless color_present?```

2018-11-24 13:16 UTC, Patriarh22 commented on objects/eugene.doroshenko/task5.rb
> +  attr_accessor :input_text, :chosen_color
Побажання по ексесорам таке ж саме, як і в ```task4_6.rb```

2018-11-24 13:16 UTC, Patriarh22 commented on objects/eugene.doroshenko/colors.rb
> +      }.freeze
Фрізити потрібно значення, які знаходяться в константах, для того, щоб їх не можна було модифікувати. Значення в методах фрізить не потрібно

2018-11-24 13:16 UTC, Patriarh22 commented on objects/eugene.doroshenko/task5.rb
> +  include ColorizeText
Не потрібно виконувати ```include ColorizeText```. Якщо є така необхідність подібним чином організувати код, тоді ```require_relative "colors"``` буде достатньо, тобто ```ColorizeText::ColorList.list_of_colors``` виконається і без інклуда. В даному випадку, хеш із метода ```list_of_colors``` достатньо буде покласти в константу в класі ```ColorInputText```

2018-11-25 09:32 UTC, doroshenko-e commented on objects/eugene.doroshenko/task5.rb
> +  include ColorizeText
видалено

2018-11-25 09:32 UTC, doroshenko-e commented on objects/eugene.doroshenko/colors.rb
> +      }.freeze
видалено

2018-11-25 09:32 UTC, doroshenko-e commented on objects/eugene.doroshenko/task5.rb
> +  attr_accessor :input_text, :chosen_color
видалено

2018-11-25 09:33 UTC, doroshenko-e commented on objects/eugene.doroshenko/task5.rb
> +    raise "there's no such color in hash" if color_present? == false
змінено

2018-11-25 09:33 UTC, doroshenko-e commented on objects/eugene.doroshenko/task4_6.rb
> +  attr_accessor :el1, :el2
видалено

2018-11-26 08:30 UTC, Patriarh22 requested changes

2018-11-26 08:30 UTC, Patriarh22 commented on objects/eugene.doroshenko/math_operations_list.rb
> +    }.freeze
Фрізити потрібно тільки константи, в методі ```freeze``` - зайвий

2018-11-26 09:03 UTC, doroshenko-e commented on objects/eugene.doroshenko/math_operations_list.rb
> +    }.freeze
блін, забув, що й там константу змінив на метод, дякую. зараз виправлю

2018-11-26 09:19 UTC, doroshenko-e commented on objects/eugene.doroshenko/math_operations_list.rb
> +    }.freeze
в мене питання. щодо такої ситуації
Краще зробити новий комміт, чи намагатись змінити свій останній комміт?

2018-11-26 10:41 UTC, merged