Added homework 3
MastersAcademy/ruby-course-2018 pull request #37
Opened 2018-12-02 10:52 UTC by vladvovk2

2018-12-03 21:52 UTC, slenderock requested changes

2018-12-03 21:52 UTC, slenderock commented on db_dsl_active_record/workshop/.ruby-version
> -2.5
поверни всі файли що були в папці воркшоп назад. Якщо я замержу коміт з видаленням цих файлів, і всіх полізуть конфлікти

2018-12-03 21:52 UTC, slenderock commented on db_dsl_active_record/workshop/.ruby-version
> -2.5
тобто ті файли, що Юра створював мають залишитись на своїх місцях

2018-12-08 10:09 UTC, vladvovk2 commented on db_dsl_active_record/workshop/.ruby-version
> -2.5
Видалив всі папки всіх студентів.  Залишив тільки свою та додав workshop. Надіюсь, так нормально буде

2018-12-10 17:44 UTC, closed without merging