My homework ActiveRecord Metelap.Vlad
MastersAcademy/ruby-course-2018 pull request #38
Opened 2018-12-03 12:22 UTC by westnick2

My homework ActiveRecord Metelap.Vlad

2018-12-03 21:59 UTC, slenderock requested changes

2018-12-03 21:59 UTC, slenderock commented on db_dsl_active_record/vlad.metelap/workshop/app/models/book.rb
> +  attr_accessor :name, :author, :category, :year
навіщо тобі тут аттр аксесор? те ж саме за інші файли

2018-12-04 17:10 UTC, westnick2 commented on db_dsl_active_record/vlad.metelap/workshop/app/models/book.rb
> +  attr_accessor :name, :author, :category, :year
resolved

2018-12-10 17:46 UTC, slenderock approved these changes

2018-12-10 17:46 UTC, merged