Add homework# 3
MastersAcademy/ruby-course-2018 pull request #39
Opened 2018-12-04 10:17 UTC by daglus

Хотел сделать еще вывод плейлиста,в который добавлен трек но не разобрался до конца

2018-12-09 13:55 UTC, Patriarh22 requested changes

2018-12-09 13:55 UTC, Patriarh22 commented on db_dsl_active_record/nikolay.braslavets/app/models/user.rb
> +  def show_all_playlists
Трохи дивна логіка, коли у методі інстанса (тобто у конкретного ```user```'a), викликається метод, який шукає випадкового (станнього) ```user```'a і у нього шукає ```playlist```'и. Тут логічніше інстанс юзера шукати ззовні, а в методі залишити цей функціонал
```ruby
  playlists.map { |pl| puts "Name: #{pl.name}\nDecsription: #{pl.description}" }
```
Те ж саме стосується метода ```show_all_songs```

2018-12-09 13:55 UTC, Patriarh22 commented on db_dsl_active_record/nikolay.braslavets/db/migrate/20181202210103_create_playlists.rb
> +    add_column :playlists, :user_id, :integer
Для зовнішніх ключів (типу ```user_id```) потрібно додавати індекси

2018-12-09 13:55 UTC, Patriarh22 commented on db_dsl_active_record/nikolay.braslavets/run.rb
> +User.create(first_name: '  Nikolay' ,
Метод ```create``` повертає об'єкт, тобто в даному випадку новоствореного ```user```'a , з яким можна далі виконувати дії, тобто не потрібно робити додатковий запит в базу, ось тут:
```ruby
  current_user = User.last
```

2018-12-09 13:55 UTC, Patriarh22 commented on db_dsl_active_record/nikolay.braslavets/run.rb
> +                          playlist_id: "#{current_user.playlists.last}")
Тут також можна використати об'єкт, створений в цьому місці
```ruby
  current_user.playlists.create(name: 'For work none hardly', description: 'Indian pop songs from inidian film')
```

2018-12-10 20:44 UTC, daglus commented on db_dsl_active_record/nikolay.braslavets/run.rb
> +                          playlist_id: "#{current_user.playlists.last}")
Не много запутался и буду благодарен за объяснения куда не там сворачиваю или что не так понял, сейчас run.rb выглядит вот так:

`require 'pry'
require './config/initializers/database'

User.create(first_name: '  Nikolay' ,
            last_name: 'Braslavets'  ,
            email: 'mail@wxmple.com')

puts User.last.full_name_and_email

# Return Validation failed: Email has already been taken
# User.create!(first_name: '  Nikolay' , last_name: 'Braslavets'  , email: 'mail@wxmple.com')
# User.last.full_name_and_email
#
User.last.playlists.create(name: 'For work hardly',
                              description: 'Indian pop songs')

User.last.playlists.create(name: 'For work none hardly',
                              description: 'Indian pop songs from inidian film')

# Return  Validation failed: Name playlist has already been taken
# User.last.playlists.create!(name_playlist: 'For work none hardly', description: 'Indian pop songs from inidian film')

User.last.show_all_playlists

User.last.songs.create(artist: 'Moize NC',
                          name: 'Master of pupets',
                          genre: 'Shophop',
                          playlist: "#{User.last.playlists.last}")

User.last.songs.create(artist: 'Bronze NC',
                          name: 'Master of duckets',
                          genre: 'Hlophlop',
                          playlist: "#{User.last.playlists.first}")


User.last.show_all_songs
`

Дохожу до момента создания песни и не пойму что упустил, так как song не создается и выпадает с ошибкой

> /bundle/gems/activerecord-5.2.1/lib/active_record/associations/association.rb:238:in `raise_on_type_mismatch!': Playlist(#47189841819940) expected, got "#<Playlist:0x000055d67b917650>" which is an instance of String(#47189832621600) (ActiveRecord::AssociationTypeMismatch)

2018-12-10 20:57 UTC, Patriarh22 commented on db_dsl_active_record/nikolay.braslavets/run.rb
> +                          playlist_id: "#{current_user.playlists.last}")
Ти ось тут 
```ruby
  "#{User.last.playlists.last}"
```
виконуєш інтерполяцію, тобто із об'єкта ActiveRecord робиш строку, прибери ```"#{}```

2018-12-13 07:22 UTC, Patriarh22 requested changes

2018-12-13 07:22 UTC, Patriarh22 commented on db_dsl_active_record/nikolay.braslavets/app/models/user.rb
> +    songs.map do |pl| puts "Song: #{pl.artist} - #{pl.name} / #{pl.genre} genre\nfound in palylist #{pl.playlist}"
Якщо передаєш блок у вигляді ```do ... end```, то ```puts ...``` повинен знаходитись на наступному рядку

2018-12-13 07:25 UTC, Patriarh22 requested changes

2018-12-13 07:25 UTC, Patriarh22 commented on db_dsl_active_record/nikolay.braslavets/app/models/user.rb
> +    songs.map do |pl| puts "Song: #{pl.artist} - #{pl.name} / #{pl.genre} genre\nfound in palylist: #{pl.playlist.name}"
Якщо передаєш блок у вигляді ```do ... end```, то ```puts ...``` повинен знаходитись на наступному рядку

2018-12-14 07:06 UTC, merged