hw1
MastersAcademy/ruby-course-2018 pull request #4
Opened 2018-11-08 18:36 UTC by VladZelenko

2018-11-08 18:57 UTC, shuforov commented on ruby_basic/Vlad.Zelenko/HW1/task4.rb
> +bool = if bool == "true" || true
https://github.com/rubocop-hq/ruby-style-guide#syntax
Краще використовувати данну синтаксичну структуру
result =
  if condition
    x
  else
    y
  end

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task1.rb
> +  }
Freeze mutable objects assigned to constants.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task1.rb
> +  def timeZoneChange
Use snake_case for symbols, methods and variables.
https://github.com/rubocop-hq/ruby-style-guide#snake-case-symbols-methods-vars

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task2.rb
> +  }
Freeze mutable objects assigned to constants.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task3.rb
> +
TASK #3 **
Скрипт приймає два масиви та виводить їх спільні елементи

Your script doesn't accept any arguments.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task2.rb
> +  def getFileToString
Use snake_case for symbols, methods and variables.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task2.rb
> +  def paintText
Use snake_case for symbols, methods and variables.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task2.rb
> +text_color = TextColor.new("red", "test.txt")
TASK #2 ****
Скрипт приймає код кольору в виді тексту та назву файла, після чого виводить текст з файла в заданому кольорі

Input example: ruby yourscript.rb red some.txt

Your script doesn't accept any arguments.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task4.rb
> +# bool = gets.chomp
Your script should accept arguments

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task4.rb
> +bool =
This variable always will be 1

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task4.rb
> +p ObjectSpace.memsize_of(bool.to_s)
String version should be "true" or "false". Not "1" or "0".

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task5.rb
> +  def searchStrFile(fileName)
Use snake_case for symbols, methods and variables.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task6.rb
> +class CalcNumbers
TASK #6 *
Скрипт створює клас для роботи з числами. Треба реалізувати в класі методи суми, різниці, ділення, множення

Input example: ruby yourscript.rb 5 10 sum

2 of your methods accept arguments, but not 4, All methods should accept arguments like your division or subtraction.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task7.rb
> +# p [1,4,6,7,8,9,23,6,56].sample
Your script doesn't accept any arguments.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task7.rb
> +  def randNumbArr(*arr)
Use snake_case for symbols, methods and variables.

2018-11-08 21:21 UTC, Flippylolz commented on ruby_basic/Vlad.Zelenko/HW1/task1.rb
> +class TimeZone
TASK #1 ***
Скрипт приймає таймзону в виді тексту та виводить поточний час в заданій таймзоні

Input example: ruby yourscript.rb UTC

Your script doesn't accept any arguments.

2018-11-08 21:41 UTC, Flippylolz commented
You can use ARGV or gets.chomp to accept arguments from console.

2018-11-08 21:42 UTC, slenderock requested changes

2018-11-08 21:42 UTC, slenderock commented on ruby_basic/Vlad.Zelenko/HW1/task2.rb
> +  #На випадок якщо знадобиться текст до покраски
Ніколи не залишай коментарі в коді українською або російською мовою. В програмуванні це моветон

2018-11-08 21:42 UTC, slenderock commented on ruby_basic/Vlad.Zelenko/HW1/task2.rb
> +  #На випадок якщо знадобиться текст до покраски
Лише англійською

2018-11-11 21:31 UTC, Isildy reviewed
(a = gets.to_i, b = gets.to_i)
 Данная структура не верна синассически, она используется для обозначение дефолтнго значения. На момент создания инстанса класа gets.to_i віражения значения еще нет. В данной ситуации нужно принимать значения при инициализации класа, к примеру.

2018-11-15 18:10 UTC, YuriiRudenko requested changes

2018-11-15 18:10 UTC, YuriiRudenko commented on ruby_basic/Vlad.Zelenko/HW1/task3.rb
> +first_arr = gets.chomp.split(",").map(&:to_i)
може бути проблема, коли вводять не тільки числа

2018-11-15 18:10 UTC, YuriiRudenko commented on ruby_basic/Vlad.Zelenko/HW1/task4.rb
> +  if bool == "true" || true
```ruby
['true', true].include? bool
```

2018-11-15 18:10 UTC, YuriiRudenko commented on ruby_basic/Vlad.Zelenko/HW1/task4.rb
> +  if bool == "true" || true
тут завжди буде або 'true' або '1' або 'false' або '0'

2018-11-15 18:10 UTC, YuriiRudenko commented on ruby_basic/Vlad.Zelenko/HW1/task5.rb
> +puts search.search_str_file("test.txt") { "и, жизнь ласкает тишиной, " }
рядок і назва файла повинні задаватись з консолі

2018-11-15 18:10 UTC, YuriiRudenko commented on ruby_basic/Vlad.Zelenko/HW1/task6.rb
> +    @a.to_f / @b
буде проблема, коли @b == 0
Такий варіант треба обробляти

2018-11-15 18:10 UTC, YuriiRudenko commented on ruby_basic/Vlad.Zelenko/HW1/task6.rb
> +  def initialize(arr)
для того, щоб в клас не прийшло нічого лишнього краще так
```ruby
def initialize(a, b)
  @a = a.to_i
  @b = b.to_i
end
```
а при виклику передати всі аргументи які прийшли
```ruby
CalcNumbers.new(*ARGV)
```

2018-11-15 18:10 UTC, YuriiRudenko commented on ruby_basic/Vlad.Zelenko/HW1/task8.rb
> +p ARGV.map! { |x| x.to_i }.sort.reverse
немає причини використовувати мутатор
```ruby
map!
```
достатньо
```ruby
map
```

2018-11-16 12:19 UTC, closed without merging