add_workshop_and_hometask
MastersAcademy/ruby-course-2018 pull request #40
Opened 2018-12-05 09:49 UTC by MrGaoler

2018-12-09 15:27 UTC, Patriarh22 requested changes

2018-12-09 15:27 UTC, Patriarh22 commented on db_dsl_active_record/andrii.gluschak/app/models/post.rb
> +  has_many :image, as: :imageable
Зв'язок ```has_many``` передбачає множину, тому краще так
```ruby
  has_many :images, as: :imageable
```

2018-12-09 15:27 UTC, Patriarh22 commented on db_dsl_active_record/andrii.gluschak/db/migrate/20181203135642_create_posts.rb
> +      t.integer :user_id
На зовнішні поля, такі як ```user_id``` потрібно додавати індекси

2018-12-09 15:27 UTC, Patriarh22 commented on db_dsl_active_record/andrii.gluschak/db/migrate/20181204121423_create_images.rb
> +      t.integer :user_id
У поліморфної сутності повинно бути два поля, які вказують на ```id``` і ```type``` сутності, з якою встановлюється зв'язок. І звісно, повинен бути індекс відразу на обидва цих поля

2018-12-09 15:27 UTC, Patriarh22 commented on db_dsl_active_record/andrii.gluschak/hometask.md
> +до наступного заняття треба:
це зайвий файл

2018-12-09 15:27 UTC, Patriarh22 commented on db_dsl_active_record/andrii.gluschak/run.rb
> +User.create!(first_name: ' Somebody    ', last_name: 'Who')
Метод ```create``` повертає створений об'єкт, тому робити зайвий запит (```User.last```) не потрібно.
В пулл реквесті є ще модель ```Image```, потрібно продемонструвати взаємодію з нею.

2018-12-09 15:27 UTC, Patriarh22 commented on db_dsl_active_record/workshop/Gemfile
>  source 'https://rubygems.org'
Файл не відноситься до твоєї робочої директорії, його треба прибрати

2018-12-09 15:27 UTC, Patriarh22 commented on db_dsl_active_record/workshop/run.rb
>  require 'pry'
Файл теж не відноситься до твоєї робочої директорії, його треба прибрати

2018-12-21 17:02 UTC, Patriarh22 requested changes

2018-12-21 17:02 UTC, Patriarh22 commented on db_dsl_active_record/andrii.gluschak/run.rb
> +Image.create!(url:'test', imageable_id: '1', imageable_type: 'jpeg')
```imageable_type``` - це по суті назва моделі до до якої відноситься поліморфна сутність. ЇЇ можна створювати наприклад таким чином:
```ruby
  user = User.create!(first_name: 'Somebody', last_name: 'Anyone')
  Image.create!(url:'test', imageable: user)
```

2018-12-21 17:02 UTC, Patriarh22 commented on db_dsl_active_record/andrii.gluschak/run.rb
> +Post.create!(title: 'head', body: 'text', user_id: '1')
Краще використати конструкцію 
```ruby
  user = User.create!(first_name: 'Somebody', last_name: 'Anyone')
  user.posts.create(...)
```

2019-01-04 13:13 UTC, slenderock requested changes

2019-01-04 13:13 UTC, slenderock commented on db_dsl_active_record/workshop/run.rb
>  require 'pry'
Досі не пофікшено

2019-01-04 13:13 UTC, slenderock commented on rack/andrii.gluschak/config.ru
> +run Proc.new { |env| ['200', {'Content-Type' => 'text/html'}, ['get rack\'d']] }
це просто темплейт з репо. Не дуже гуд виходить, якщо ми замержимо таке, бо потім не можна буде швидко побачити чи домашка готова чи ні. Тому давай ти додаси сюди ще й воркшоп і все разом замержимо?

Але зробити треба якнайшвидше, щоб не попало сюди ще нових дз

2019-02-07 10:11 UTC, closed without merging