workshop 1
MastersAcademy/ruby-course-2018 pull request #42
Opened 2018-12-14 00:41 UTC by TarasTurchenko

2018-12-14 13:52 UTC, YuriiRudenko requested changes

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/Rakefile
> +    filename = "db/schema.rb"
в константу + в одинарних лапках

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/Rakefile
> +    File.open(filename, "w:utf-8") do |file|
одинарні
Привикай юзать подвійні тільки коли вони дійсно треба

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/Rakefile
> +    timestamp = Time.now.strftime("%Y%m%d%H%M%S")
те саме з лапками

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/models/category.rb
> +  validates_presence_of :name
не юзай такий синтаксис, він вже застарів

```ruby
validates :name, presence: true
```

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/models/movie.rb
> +  belongs_to :author, class_name: 'User', primary_key: 'id', foreign_key: 'author_id'
```primary_key: :id, foreign_key: :author_id```

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/models/movie.rb
> +  validates :rating, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100}
пробіли між дужками

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/models/movie.rb
> +  validates :rating, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100}
прожени весь код цього реквеста через рубокоп

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/models/user.rb
> +  has_many :movies, class_name: 'Movie', primary_key: 'id', foreign_key: 'author_id'
```belongs_to :author, class_name: 'User', primary_key: 'id', foreign_key: 'author_id'```

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/views/app_view.rb
> +  attr_accessor :categories_view, :movies_view, :current_user
подивись конвеншн оформлення коду

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/views/app_view.rb
> +  attr_accessor :categories_view, :movies_view, :current_user
це про порядок блоків

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/views/auth_view.rb
> +    begin
якщо rescue відноситься до всього коду в методі то можна так
```ruby
def registration(login, password)
  User.create!(login: login, password: password)
rescue ActiveRecord::RecordInvalid
  puts "\n  #{$!}"
  do_auth
end
```

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/models/user.rb
> +  validates_presence_of :password
```ruby
validates :password, :login, presence: true
```

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/views/auth_view.rb
> +        puts
?

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/views/auth_view.rb
> +    case selected_menu_option.to_s
зроби різними методами
```ruby
def auth
  if respond_to? selected_menu_option.to_sym
    send(selected_menu_option.to_sym)
  else
    on_incorrect_option_selected
    auth
  end
end

def login
...
end

def registration
...
end
```

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/views/auth_view.rb
> +    begin
якщо блок між begin і rescue - це весь метод, то можна так:
```ruby
def login(login, password)
  user = User.find_by(login: login)
  return user if password == user.password
  puts " Incorrect password"
  auth
rescue ActiveRecord::RecordNotFound
  puts " Not found user with login '#{login}'\n"
  auth
end
```

2018-12-14 13:52 UTC, YuriiRudenko commented on db_dsl_active_record/taras.turchenko/app/views/categories_view.rb
> +    case selected_menu_option.to_s
так само в різні методи

2018-12-14 18:54 UTC, TarasTurchenko commented on db_dsl_active_record/taras.turchenko/Rakefile
> +    filename = "db/schema.rb"
То ж ми копіпастили) Ща все поправлю

2018-12-14 23:41 UTC, TarasTurchenko commented on db_dsl_active_record/taras.turchenko/app/models/user.rb
> +  has_many :movies, class_name: 'Movie', primary_key: 'id', foreign_key: 'author_id'
На рахунок цього не дуже зрозумів. Тут belongs_to?

2018-12-16 12:52 UTC, TarasTurchenko commented
Done. Please check

2018-12-19 15:13 UTC, slenderock approved these changes

2018-12-19 15:13 UTC, merged