Homework ruby basic
MastersAcademy/ruby-course-2018 pull request #5
Opened 2018-11-09 00:07 UTC by doroshenko-e

hope done

2018-11-09 10:33 UTC, slenderock requested changes

2018-11-09 10:33 UTC, slenderock commented on ruby_basic/eugene.doroshenko/task3.rb
> +		return array
в рубі по дефолту повертається(ретурниться) остання строчка в методі, тому можна не писати слова `return`

2018-11-09 10:33 UTC, slenderock commented on ruby_basic/eugene.doroshenko/task4.rb
> +		mem_size_str = ObjectSpace.memsize_of(@bln_string)
тут ти присваюєш в змінну mem_size_str результат, але змінну ніде не використовуєш. В твоєму варіанту це присвоєння не потрібне. Раджу прибрати

2018-11-09 10:33 UTC, slenderock commented on ruby_basic/eugene.doroshenko/task4.rb
> +	start_boolean = BooleanToStrInt.new
описувати операції над класом, а саме створення обєкту, та виклик методів класу краще поза класом(після енду)

2018-11-09 11:55 UTC, doroshenko-e commented on ruby_basic/eugene.doroshenko/task3.rb
> +		return array
это я понимаю, поэтому и указал "return array", иначе возвращаться будет "element = gets.chomp"

2018-11-09 12:40 UTC, slenderock requested changes

2018-11-09 12:40 UTC, slenderock commented on ruby_basic/eugene.doroshenko/task3.rb
> +		return array
```
def list_of_elements
  array = []
  element = gets.chomp
  while element.present?
    array = array.push element
    element = gets.chomp
  end
  puts "Array is: #{array}"
  array
end
```

2018-11-09 12:43 UTC, slenderock commented on ruby_basic/eugene.doroshenko/task3.rb
> +		return array
Дай будь ласка знати, якщо є питання по запропонованих мною змінах

2018-11-09 13:14 UTC, doroshenko-e commented on ruby_basic/eugene.doroshenko/task3.rb
> +		return array
Все понятно))

2018-11-09 13:28 UTC, doroshenko-e reviewed
Changed tasks 3, 4 , 6 and 8 Object.new now after class
return deleted
deleted unused values

2018-11-10 06:47 UTC, doroshenko-e reviewed
return deleted

2018-11-12 15:16 UTC, merged