Workshop 2. Rack
MastersAcademy/ruby-course-2018 pull request #53
Opened 2019-01-23 15:30 UTC by vladvovk2

2019-01-30 13:31 UTC, YuriiRudenko requested changes

2019-01-30 13:31 UTC, YuriiRudenko commented on rack/vlad.vovk/app/models/pet.rb
> +    if @health < 0
тернарний оператор підійде
```ruby
@health.negative? ? 0 : @health
```

2019-01-30 13:31 UTC, YuriiRudenko commented on rack/vlad.vovk/app/models/pet.rb
> +    if value < MIN
у тебе `self.health -= STEP` виконується в любому випадку

2019-01-30 13:31 UTC, YuriiRudenko commented on rails/vlad.vovk/lection_hw/action_cable/app/controllers/users_controller.rb
> +    if @user.save
```if user.create(user_params)```

2019-01-30 13:31 UTC, YuriiRudenko commented on rails/vlad.vovk/lection_hw/action_cable/app/models/message.rb
> +  after_create_commit {
небезпечно юзать такі коллбеки. Краще юзай стандартні колбеки activerecord
```ruby
after_create :broadcast

private

def broadcast
  MessageBroadcastJob.perform_later(self)
end
```

2019-01-30 13:31 UTC, YuriiRudenko commented on rails/vlad.vovk/lection_hw/action_cable/config/routes.rb
> +  get 'signup', to: 'users#new',        as: 'signup'
можна symbol юзать
```ruby
get :signup, to: 'users#new', as: :signup
```

2019-01-30 16:58 UTC, vladvovk2 commented on rails/vlad.vovk/lection_hw/action_cable/app/models/message.rb
> +  after_create_commit {
Виправив

2019-01-30 16:58 UTC, vladvovk2 commented on rails/vlad.vovk/lection_hw/action_cable/config/routes.rb
> +  get 'signup', to: 'users#new',        as: 'signup'
Виправив

2019-01-30 16:58 UTC, vladvovk2 commented on rack/vlad.vovk/app/models/pet.rb
> +    if value < MIN
Виправив

2019-01-30 16:59 UTC, vladvovk2 commented on rack/vlad.vovk/app/models/pet.rb
> +    if @health < 0
Виправив

2019-01-30 17:06 UTC, vladvovk2 commented on rails/vlad.vovk/lection_hw/action_cable/app/controllers/users_controller.rb
> +    if @user.save
Виправив

2019-01-31 08:54 UTC, YuriiRudenko requested changes

2019-01-31 08:54 UTC, YuriiRudenko commented on rails/vlad.vovk/lection_hw/action_cable/app/models/message.rb
> +  after_create_commit :broadcast
тобі потрібно ловити івент від ActiveRecordб а не від транзакції в базі
```ruby
after_create :broadcast
```

2019-01-31 08:54 UTC, YuriiRudenko commented on rails/vlad.vovk/lection_hw/action_cable/app/models/user.rb
> +  has_many :messages, dependent: :destroy
а точно треба видаляти меседжі? Тоді при видаленні юзера в чатах буде історія виглядати як мінімум дивно

2019-01-31 08:54 UTC, YuriiRudenko commented on rails/vlad.vovk/lection_hw/action_cable/app/models/user.rb
> +    self.email = self.email.delete(' ').downcase
self.email.strip.downcase

2019-01-31 09:59 UTC, vladvovk2 commented on rails/vlad.vovk/lection_hw/action_cable/app/models/user.rb
> +    self.email = self.email.delete(' ').downcase
Виправив

2019-01-31 09:59 UTC, vladvovk2 commented on rails/vlad.vovk/lection_hw/action_cable/app/models/user.rb
> +  has_many :messages, dependent: :destroy
Так і є) Виправив

2019-01-31 10:00 UTC, vladvovk2 commented on rails/vlad.vovk/lection_hw/action_cable/app/models/message.rb
> +  after_create_commit :broadcast
after_create не релогає відобреження повідомлень

2019-02-04 11:10 UTC, merged