Lessons 4.1 (Tanagochi) , Add workshop files
MastersAcademy/ruby-course-2018 pull request #54
Opened 2019-01-24 11:32 UTC by daglus

2019-02-01 10:14 UTC, daglus commented
Удалил лишние файлы, что при коммите залетели с папок других юзеров.

2019-02-04 08:14 UTC, YuriiRudenko commented
3. Перенести всі моделі, які були імплементовані вами на попередніх заняттях в рейлс проект.

2019-02-13 07:40 UTC, YuriiRudenko requested changes

2019-02-13 07:40 UTC, YuriiRudenko commented on rails/nikolay.braslavets/workshop_hw/wan_password/Gemfile
> +ruby '2.5.1'
Прибираєм

2019-02-13 07:40 UTC, YuriiRudenko commented on rack/nikolay.braslavets/.env
> +RAILS_ENV=development
файл повинен бути в .gitignore

2019-02-13 07:40 UTC, YuriiRudenko commented on rack/nikolay.braslavets/app/models/pet.rb
> +        health: health,
відступи

2019-02-13 07:40 UTC, YuriiRudenko commented on rails/nikolay.braslavets/workshop_hw/wan_password/app/controllers/application_controller.rb
> +      @current_user = nil
гоч це генерить гем, воно не потрібне

2019-02-13 07:40 UTC, YuriiRudenko commented on rails/nikolay.braslavets/workshop_hw/wan_password/config/routes.rb
> +  get 'signup', to: 'users#new', as: 'signup'
```ruby
get :signup, to: 'users#new', as: :signup
```

2019-02-13 13:22 UTC, daglus commented on rack/nikolay.braslavets/.env
> +RAILS_ENV=development
Убрал, файл удалил из репо

2019-02-13 13:29 UTC, daglus commented on rack/nikolay.braslavets/app/models/pet.rb
> +        health: health,
Я не совсем понял что с ними не так. Это кусок из воркшопа который не трогал, и сам рубимайн так форматирует,  не подскажешь ?

Или такой вид имелся ввиду?

  def to_json
    {health: health,
     hunger: hunger,
     happiness: happiness,
     sleepiness: sleepiness,
     mood: mood,
     event: event,
     dead: dead?}
  end

2019-02-16 08:07 UTC, YuriiRudenko commented on rack/nikolay.braslavets/app/models/pet.rb
> +        health: health,
малось на увазі відступ повинен бути 2 пробіли а не 4

2019-02-16 08:08 UTC, merged