HW5
MastersAcademy/ruby-course-2018 pull request #56
Opened 2019-01-25 20:31 UTC by st3p

2019-01-30 15:12 UTC, YuriiRudenko requested changes

2019-01-30 15:12 UTC, YuriiRudenko commented on rails/vazgen.bakhchagulian/lection_hw/app/controllers/application_controller.rb
> +      @current_user = nil
це генерить скафолд, але воно лишнє

2019-01-30 15:12 UTC, YuriiRudenko commented on rails/vazgen.bakhchagulian/lection_hw/app/models/pet.rb
> +        health: health,
відступи

2019-01-30 15:12 UTC, YuriiRudenko commented on rails/vazgen.bakhchagulian/lection_hw/app/models/pet.rb
> +    if @health < 0
`@health.negative? ? 0 : @health

2019-01-30 15:12 UTC, YuriiRudenko commented on rails/vazgen.bakhchagulian/lection_hw/app/models/pet.rb
> +      self.health -= STEP
`self.health -= STEP` цей код виконується в обох випадках

2019-02-06 11:56 UTC, st3p commented on rails/vazgen.bakhchagulian/lection_hw/app/models/pet.rb
> +      self.health -= STEP
Виправив, трохи нижче

2019-02-13 07:31 UTC, merged