Rails lection_hw
MastersAcademy/ruby-course-2018 pull request #57
Opened 2019-01-25 21:17 UTC by EugeneTymoshenko

2019-01-28 11:28 UTC, YuriiRudenko requested changes

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/Gemfile
> +ruby '2.5.1'
а для чого лочить гемфайл на певній версії рубі?

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/app/controllers/application_controller.rb
> +      @current_user ||= User.find_by(id: session[:user_id])
відступи криві

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/app/controllers/sessions_controller.rb
> +    user = User.find_by_email(params[:email])
такий виклик депрекейтед
```ruby
user = User.find_by(email: params[:email])
```

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125190351_create_playlists.rb
> +    create_table :playlists
в міграціях в рельсах можна так, як в тебе в юзерах написано

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125190622_create_songs.rb
> +    create_table :songs
в міграціях в рельсах можна так, як в тебе в юзерах написано

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125190741_create_artists.rb
> +    create_table :artists
в міграціях в рельсах можна так, як в тебе в юзерах написано

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125191733_add_playlist_ref_to_users.rb
> +    add_reference :users, :playlist, foreign_key: true
старайся розробляти так, щоб міграцій було мінімум. Наприклад, референс можна було вказати в створенні таблиці

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125192518_create_music_playlists_join_table.rb
> +    create_table :playlists_songs, :id => false do |t|
```ruby
id: false
```

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125192518_create_music_playlists_join_table.rb
> +    add_index :playlists_songs, [:playlist_id, :song_id]
цей індекс треба зробити primary key

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125192518_create_music_playlists_join_table.rb
> +    add_index :playlists_songs, [:playlist_id, :song_id]
плюс він повинен бути unique

2019-01-28 11:28 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125192518_create_music_playlists_join_table.rb
> +    add_index :playlists_songs, [:playlist_id, :song_id]
а поля повинні бути null: false

2019-01-30 12:03 UTC, sunstoryx commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125192518_create_music_playlists_join_table.rb
> +    add_index :playlists_songs, [:playlist_id, :song_id]
Привiт! А що саме мається на увазi пiд "цей індекс треба зробити primary key"?

2019-01-30 15:11 UTC, YuriiRudenko commented on rails/eugene.tymoshenko/lection_hw/shop/db/migrate/20190125192518_create_music_playlists_join_table.rb
> +    add_index :playlists_songs, [:playlist_id, :song_id]
у тебе комбінація полей :playlist_id, :song_id повинна бути основним ключем таблиці, якщо id немає

2019-02-04 08:06 UTC, merged