HW Workshop Rack / Rails lesson HW / Rails workshop HW
MastersAcademy/ruby-course-2018 pull request #58
Opened 2019-01-27 17:14 UTC by doroshenko-e

2019-02-05 15:33 UTC, slenderock requested changes

2019-02-05 15:33 UTC, slenderock commented on rails/eugene.doroshenko/workshop_hw/.env
> +RAILS_ENV=development
Підтягни останні зміни з основного репо. Я там додав .env в гітігнор проекту. Тут він теж зникне тоді

2019-02-06 08:20 UTC, slenderock requested changes

2019-02-06 08:20 UTC, slenderock commented on rails/eugene.doroshenko/workshop_hw/.env
> +RAILS_ENV=development
Точно. Ти ж його запушив вже в репо, тому треба зробити ось такий трюк
https://alvinalexander.com/git/git-rm-file-git-repository-dont-track-accidentally-added

2019-02-06 08:20 UTC, slenderock commented on rails/eugene.doroshenko/workshop_hw/.env
> +RAILS_ENV=development
Це прибере файл з переліку файлів які треба трекати. І він зникне видалиться з репо але залишиться в тебе локально

2019-02-07 20:31 UTC, doroshenko-e commented on rails/eugene.doroshenko/workshop_hw/.env
> +RAILS_ENV=development
виправлю це при наступному комміті, коли воркшоп зроблю

2019-05-29 15:11 UTC, closed without merging