homework
MastersAcademy/ruby-course-2018 pull request #6
Opened 2018-11-09 10:21 UTC by MrGaoler

first task not done

2018-11-09 10:38 UTC, slenderock requested changes

2018-11-09 10:38 UTC, slenderock commented on ruby_basic/andrii.gluschak/task#2.rb
> +
Тут використаний неправильний спосіб табуляції. Всі ці операції є однорівневими, і не мають табулюватись. Табуляцію треба додавати тільки для внутрянки методу, блоку, класу або модулю. В інших кейсах в цьому немає потреби

2018-11-09 10:38 UTC, slenderock commented on ruby_basic/andrii.gluschak/ task#1.rb
> +}
підозрюю що це завдання не виконане. Бачу тільки приствоєння змінних

2018-11-09 11:44 UTC, Patriarh22 commented on ruby_basic/andrii.gluschak/task#3.rb
> +  array1 = []
Не потрібно сетить ```array1 = []``` і ```array2 = []```, метод ```split``` і так поверне масив

2018-11-09 11:44 UTC, Patriarh22 commented on ruby_basic/andrii.gluschak/task#3.rb
> +  array3 = array1 & array2
можна не поміщати результат в змінну ```array3```, достатньо виконати ```puts array1 & array2```. Доречі відступи (табуляція) в файлі зайві.

2018-11-09 12:10 UTC, Patriarh22 commented on ruby_basic/andrii.gluschak/task#6.rb
> +  when "plus"
Не потрібна табуляція, ```when``` пишеться на рівні із ```case```

2018-11-09 12:10 UTC, Patriarh22 commented on ruby_basic/andrii.gluschak/task#6.rb
> +  a = gets.chomp.to_i
Потрібно намагатись зрозуміло іменувати змінні, наприклад ```a``` можна було назвати ```first_value```, ```b``` -> ```second_value```, ```c``` -> ```result```

2018-11-09 12:10 UTC, Patriarh22 commented on ruby_basic/andrii.gluschak/task#6.rb
> +    c = a + b
Бажано сетити змінну ```c``` як результат виконання оператору ```case```, а не в кожній умові ```when```

2018-11-11 23:15 UTC, slenderock requested changes
Важливо: закінчити виконання 1го завдання
Бажано: поправити стайлгайд поради від @Patriarh22 та поправити табуляції

Дай знати будь ласка які проблеми блокують тебе від закінчення виконання  1го завдання.

2018-11-12 20:05 UTC, slenderock requested changes

2018-11-12 20:05 UTC, slenderock commented on ruby_basic/andrii.gluschak/task#6.rb
> +when "plus"
@MrGaoler Давай тут ще ось такий "трюк" зробимо

```
result = 
  case v
  when "plus"
    first_value + second_value
  when "minus"
    first_value - second_value
  when "sum"
    first_value * second_value
  when "div"
    first_value / second_value
  end
```

Результат обробки всередині `when` можна сетити при оголошенні кейса(те ж саме з іфами і тому подібними структурами)

2018-11-12 20:05 UTC, slenderock commented on ruby_basic/andrii.gluschak/task#1.rb
> +#p "Enter time zone"
Коменти тут не потрібні, прибери пліз

2018-11-12 20:05 UTC, slenderock commented on ruby_basic/andrii.gluschak/task#7.rb
> +  puts 'Enter mass elements'
в цьому файлі табуляції зайві

2018-11-12 20:05 UTC, slenderock commented on ruby_basic/andrii.gluschak/task#8.rb
> +array1 = []
в цьому файлі табуляції зайві

2018-11-12 20:05 UTC, slenderock commented on ruby_basic/andrii.gluschak/task#5.rb
> +file.each_with_index do |line, index|
Табуляції неправильні. Приведи до такого вигляду
```
file.each_with_index do |line, index|
  if line.chomp == text
    puts index+1
    break
  end
end
```

2018-11-12 20:40 UTC, merged