Homework Rack + rails Metelap
MastersAcademy/ruby-course-2018 pull request #64
Opened 2019-01-31 22:30 UTC by westnick2

Homework Rack + rails Metelap

2019-02-05 12:17 UTC, YuriiRudenko requested changes

2019-02-05 12:17 UTC, YuriiRudenko commented on rails/vlad.metelap/workshop_hw/wan_password/.env
> +RAILS_ENV=development
цього файла не повинно бути в репозиторії

2019-02-05 12:17 UTC, YuriiRudenko commented on rails/vlad.metelap/workshop_hw/wan_password/.gitignore
> +# See https://help.github.com/articles/ignoring-files for more about ignoring files.
треба сюди додати env файл

2019-02-05 12:17 UTC, YuriiRudenko commented on rails/wan_password/.gitignore
> +# See https://help.github.com/articles/ignoring-files for more about ignoring files.
це шо за проект не в твоїй папці?

2019-02-05 13:23 UTC, westnick2 commented on rails/vlad.metelap/workshop_hw/wan_password/.gitignore
> +# See https://help.github.com/articles/ignoring-files for more about ignoring files.
виконано

2019-02-05 13:35 UTC, westnick2 commented on rails/wan_password/.gitignore
> +# See https://help.github.com/articles/ignoring-files for more about ignoring files.
вилучив з загальної папки.
залишив у своїй

2019-02-13 07:30 UTC, YuriiRudenko commented
https://prnt.sc/mkep87

2019-03-25 21:17 UTC, closed without merging

2019-03-25 21:17 UTC, YuriiRudenko commented
not completed