Homework#1
MastersAcademy/ruby-course-2018 pull request #7
Opened 2018-11-09 12:03 UTC by ArturPashchyna

2018-11-09 12:26 UTC, alexgonor commented on ruby_basic/artur.paschyna/task3.rb
> +  a=[3,6,2,4,8,5,2,4,6]
скрипт має приймати массиви з консолі, не потрібно їх вказувати в коді

2018-11-09 12:29 UTC, alexgonor commented on ruby_basic/artur.paschyna/task8.rb
> +  a=[2,6,9,5,1,3,6,8,4,2,6,7]
те ж саме що і в Task3

2018-11-09 13:28 UTC, Patriarh22 commented on ruby_basic/artur.paschyna/task6.rb
> +class Task6
Код просто обернутий в ```class Task6```, потрібно або створювати інстанс (відповідно додавати в клас методи), або взагалі прибрати цю обгортку

2018-11-09 13:28 UTC, Patriarh22 commented on ruby_basic/artur.paschyna/task6.rb
> +  if ARGV[0]=="sum"
Не зрозуміло які значення знаходяться в ARGV[0], ARGV[1], ARGV[2], бажано насетить їх в змінні, можна так:
```ruby
  operation, first_value, second_value = ARGV
```

2018-11-10 14:04 UTC, Patriarh22 commented on ruby_basic/artur.paschyna/task6.rb
> +  if operation=="sum"
Прошу пробачення, в завданні все ж таки вказано реалізовувати через ```class```
https://github.com/MastersAcademy/ruby-course-2018/blob/master/ruby_basic/hometask.md#task-6-
Тому необхідно цю логіку реалізувати в методах інстанса класа

2018-11-10 14:06 UTC, Patriarh22 commented on ruby_basic/artur.paschyna/task8.rb
> +  puts ARGV.sort
Сортування повинно бути виконане в порядку спадання

2018-11-10 14:18 UTC, Patriarh22 commented on ruby_basic/artur.paschyna/task3.rb
> +class Task3
Якщо реалізація відбувається через структуру класу, тоді потрібно розносити логіку на методи інстанса і виконувати скріпт через ```Task3.new```

2018-11-10 14:18 UTC, Patriarh22 commented on ruby_basic/artur.paschyna/task3.rb
> +  for i in 0..l
Потрібно використовувати ітератори, тут би підійшов ```each_with_index```

2018-11-10 14:18 UTC, Patriarh22 commented on ruby_basic/artur.paschyna/task3.rb
> +class Task3
По всьому скріпту потрібно проставити правильні відступи, наприклад
```ruby
b = []
```

2018-11-11 23:11 UTC, slenderock requested changes
Дай будь ласка знати які проблеми блокують тебе від виконання завдання 1, 2, 4, 5 та чим я можу тоді допомогти

2018-11-15 18:18 UTC, YuriiRudenko commented on ruby_basic/artur.paschyna/task3.rb
> +  for i in 0..l
а ще можна l.times {}

2018-11-15 18:49 UTC, YuriiRudenko requested changes

2018-11-15 18:49 UTC, YuriiRudenko commented on ruby_basic/artur.paschyna/task6.rb
> +    if operation == "sum"
хороший підхід - розбити операції по методам

2018-11-15 18:49 UTC, YuriiRudenko commented on ruby_basic/artur.paschyna/task6.rb
> +ftr.find_the_result(ARGV[0],ARGV[1],ARGV[2])
дані в класі треба заповнювати через initialize

2018-11-15 18:49 UTC, YuriiRudenko commented on ruby_basic/artur.paschyna/task7.rb
> +  puts ARGV.sample
це працювати не буде, код повинен бути обернутий в інстанс метод

2018-11-18 21:58 UTC, slenderock requested changes

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @background = level_background
В тебе описано багацько геттерів та сеттерів, але ти їх не використовуєш. Давай використовувати :)

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +      "Your level is #{@level_number}"
використай тут геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +      "Background color is #{@background}"
використай тут геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +      "Count of enemies on level is: #{@enemies}"
використай тут геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +      "Count of ammunition is: #{@ammo}"
використай тут геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +      "Your level is #{@level_number}"
тобто ось так `"Your level is #{level_number}"`

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +      "Your altitude is: #{@alt}"
геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +      "Your fuel level is: #{@fuel}"
геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @background = level_background
Коли почнеш використовувати сеттери, помітиш що в тебе атрибути неправильно описані

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @background = level_background
Оголошений сеттер на level_background, а записаний атрибут background

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @background = level_background
Синтаксис викорстання сеттеру 
```
self.level_background = level_background
```

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @level_number = new_level_number
сеттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @background = new_background_color
сеттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @enemies = new_count_of_enemies
сеттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @ammo = new_count_of_ammunition
сеттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @alt = new_altitude
сеттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/air_fury.rb
> +    @fuel = new_count_of_fuel
сеттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/mario_game.rb
> +    "Your level is #{@level_number}"
геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/mario_game.rb
> +    "Background color is #{@background}"
геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/mario_game.rb
> +    "Enemies speed is #{@speed_enemies}"
геттер

2018-11-18 21:58 UTC, slenderock commented on objects/artur.paschyna/mario_game.rb
> +    "Enemies speed is #{@speed_enemies}"
ну і так далі, де тільки можна

2018-11-18 21:58 UTC, slenderock commented on ruby_basic/artur.paschyna/task3.rb
> +ARGV.each_with_index do |value,key|
Завдання: Скрипт приймає два масиви та виводить їх спільні елементи

В тебе ж воно кожний непарнийелемент переданий через ARGV приймає до першого масиву, кожний парний до другого. Це якось мегадивно
В завданні ж чітко сказано "приймає два масиви" В тебе ж приймає один масив, а потім ти з них робиш два. Треба переробити згідно умови

2018-11-18 21:58 UTC, slenderock commented on ruby_basic/artur.paschyna/task6.rb
> +    puts a.to_i+b.to_i
Старайся робити методи резабельними в плані повернення даних. Тобто результатом методу додавання має бути просто повернений(ретурнене) результат, а потім вже його путсать.
Приклад:
```
class Task6
  def addition(a, b)
    a.to_i + b.to_i
  end
  # implementation of other methods here
end

a, b, operation = ARGV
task = Task6.new

result = 
  case operation
  when 'sum  
    task.addition(a, b)
  # other when's
  end
puts result
```
Також зверни увагу, що немає потреби створювати новий обєкт для кожної операції, достатньо це для одного обєкту проробити.

2018-11-26 20:26 UTC, merged