HW 1 Vlad Metelap
MastersAcademy/ruby-course-2018 pull request #8
Opened 2018-11-09 12:13 UTC by westnick2

2018-11-09 12:36 UTC, alexgonor commented on ruby_basic/vlad.metelap/task4.rb
> +    puts "String #{str_bool_arg} size #{str_bool_arg.bytesize()} bytes"
краще не залишати порожніх рядків в кінці методів/класів/модулів, це ніяк не покращує читабельність коду (навіть навпаки), до того ж рубокоп буде ругатись на таке

2018-11-09 12:37 UTC, alexgonor commented on ruby_basic/vlad.metelap/task4.rb
> +res = Task4.new.convert(bool_arg)
тут можна обійтись без змінної 
`puts Task4.new.convert(bool_arg)`

2018-11-09 12:50 UTC, slenderock requested changes

2018-11-09 12:50 UTC, slenderock commented on ruby_basic/vlad.metelap/task4.rb
> +bool_arg = ARGV[0].downcase =='true'? true : false
Дивись, давай розберемось що робить ця тернарка. В випадку якщо результат ARGV[0].downcase == 'true' тру вона повертає тру, в випадку якщо фолс, повертає фолс. Навіщо потрібна подібна операція, і чому відразу не записати в змінну bool_arg результат операції ARGV[0].downcase =='true' ?

```
bool_arg = ARGV[0].downcase =='true'
```

2018-11-09 12:52 UTC, slenderock requested changes

2018-11-09 12:52 UTC, slenderock commented on ruby_basic/vlad.metelap/task5.rb
> +  def file_include?(filename,str)
Згідно конвершена знак питання в назві методу означає що метод повертає буаленове значення. Твій де метод не повертає булеан(тру/фолс)

2018-11-09 12:55 UTC, slenderock requested changes

2018-11-09 12:55 UTC, slenderock commented on ruby_basic/vlad.metelap/task8.rb
> +res = Task8.new.arr_sort(str_arr)
змінна res не використовується

2018-11-11 07:39 UTC, westnick2 commented on ruby_basic/vlad.metelap/task4.rb
> +    puts "String #{str_bool_arg} size #{str_bool_arg.bytesize()} bytes"
виправлено

2018-11-11 07:39 UTC, westnick2 commented on ruby_basic/vlad.metelap/task4.rb
> +res = Task4.new.convert(bool_arg)
виправлено

2018-11-11 07:40 UTC, westnick2 commented on ruby_basic/vlad.metelap/task4.rb
> +bool_arg = ARGV[0].downcase =='true'? true : false
переробив

2018-11-11 07:40 UTC, westnick2 commented on ruby_basic/vlad.metelap/task5.rb
> +  def file_include?(filename,str)
прибрав знак питання

2018-11-11 07:40 UTC, westnick2 commented on ruby_basic/vlad.metelap/task8.rb
> +res = Task8.new.arr_sort(str_arr)
прибрав

2018-11-11 23:02 UTC, slenderock requested changes
Поправ коменти, що я написав і замержу

2018-11-11 23:02 UTC, slenderock commented on ruby_basic/vlad.metelap/task2.rb
> +  def black;          "\e[30m#{self}\e[0m" end
В рубі не роблять однорядкові методи. Виглядає прикольно, але прийдеться звести до стандартного вигляду
```
def black
  "\e[30m#{self}\e[0m" 
end
```

2018-11-11 23:02 UTC, slenderock commented on ruby_basic/vlad.metelap/task2.rb
> +      case colour
А давай весь цей великий кейс замінимо на простий рядок який в тебе описаний в `else` :)
Правда ж гарніше буде?
```
f.each_line do |line|
  puts line.send(colour)
end
```

2018-11-11 23:02 UTC, slenderock commented on ruby_basic/vlad.metelap/task7.rb
> +    arr = str_arr.split(",")
рубі був би не рубі якби в ньому не було методів на всі випадки життя :)
раджу звернути увагу на метод [#sample](https://ruby-doc.org/core-2.2.0/Array.html#method-i-sample) для масивів

2018-11-12 06:42 UTC, westnick2 commented on ruby_basic/vlad.metelap/task2.rb
> +  def black;          "\e[30m#{self}\e[0m" end
Переробив

2018-11-12 06:42 UTC, westnick2 commented on ruby_basic/vlad.metelap/task2.rb
> +      case colour
переробив

2018-11-12 09:29 UTC, slenderock approved these changes

2018-11-12 09:29 UTC, merged

2018-11-12 09:30 UTC, slenderock commented
Все гуд, мержу